FROM golang:1.27-alpine AS builder

ARG LAST_COMMIT=local
ARG DATE=unknown
ARG BUILDTIME=0

ENV GOOS=linux
ENV CGO_ENABLED=0

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build -a -installsuffix cgo -o bin/hookd \
    -ldflags "-s -X github.com/nais/deploy/pkg/version.Revision=${LAST_COMMIT} -X github.com/nais/deploy/pkg/version.Date=${DATE} -X github.com/nais/deploy/pkg/version.BuildUnixTime=${BUILDTIME}" \
    ./cmd/hookd/


FROM alpine:3

WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /src/bin/hookd .
CMD ["/app/hookd"]
