FROM golang:1.23-alpine as builder

RUN apk add --no-cache git make curl
ENV GOOS=linux
ENV CGO_ENABLED=0

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN make kubebuilder
RUN make test
RUN make deployd-alpine


FROM alpine:3

WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /src/bin/deployd .
CMD ["/app/deployd"]
