FROM golang:1.27-alpine AS builder

ARG LAST_COMMIT=local
ARG DATE=unknown
ARG BUILDTIME=0

ENV GOOS=linux
ENV CGO_ENABLED=0

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build -a -installsuffix cgo -o bin/deploy \
    -ldflags "-s -X github.com/nais/deploy/pkg/version.Revision=${LAST_COMMIT} -X github.com/nais/deploy/pkg/version.Date=${DATE} -X github.com/nais/deploy/pkg/version.BuildUnixTime=${BUILDTIME}" \
    ./cmd/deploy/


FROM alpine:3 AS deploy

WORKDIR /app
RUN apk add --no-cache ca-certificates wget
COPY --from=builder /src/bin/deploy .
CMD ["/app/deploy"]


FROM alpine:3 AS canary-deployer

WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /src/bin/deploy .
ADD canary-deployer/deployer.sh /canary/deployer.sh
ADD canary-deployer/canary.yml /canary/resource.yml
ENV RESOURCE=/canary/resource.yml
CMD ["/canary/deployer.sh"]


FROM alpine:3 AS deploy-action

WORKDIR /app
ENV TZ="Europe/Oslo"
RUN apk add --no-cache ca-certificates curl jq
RUN curl -L -f https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64 > /usr/local/bin/yq && chmod +x /usr/local/bin/yq
COPY --from=builder /src/bin/deploy .
COPY actions/deploy/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
