ARG BASE
FROM $BASE as base
FROM alpine:3.17
WORKDIR /app

ENV TZ="Europe/Oslo"

RUN apk add --no-cache ca-certificates curl
RUN curl -L -f https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64 > /usr/local/bin/yq && chmod +x /usr/local/bin/yq

COPY --from=base /deploy .
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
