FROM ghcr.io/nais/deploy/deploy:latest
ADD canary-deployer/deployer.sh /canary/deployer.sh
ADD canary-deployer/canary.yml /canary/resource.yml
ENV RESOURCE=/canary/resource.yml
CMD ["/canary/deployer.sh"]
