@startuml component

actor developer as "Developer"
participant github as "GitHub"
participant ci as "CircleCI"
database registry as "Package registry"
participant keyd
participant hookd
collections deployd
participant kubernetes as "NAIS"

==Pre-deploy==
developer -> github: git push
github --> developer
github -> ci: Start build
ci --> github
ci -> keyd: Request tokens
keyd -> ci: Upload tokens
ci -> registry: Push image
registry --> ci

==Deploy==
ci -> github: Start deployment
github -> hookd: Webhook
hookd -> deployd: Commission deployment
hookd --> github: Update deployment status
note left: queued
deployd -> kubernetes: Deploy
kubernetes --> deployd
deployd --> hookd: Report status
hookd --> github: Update deployment status
note left: in_progress

loop until timeout or success
	deployd -> kubernetes: Check rollout status
	kubernetes --> deployd
end

deployd --> hookd: Report status
hookd --> github: Update deployment status
note left: success

@enduml
