@startuml component

actor developer as "Developer"
participant github as "GitHub"
participant ci as "Continuous Integration"
database registry as "Docker Hub"
participant hookd
collections deployd
participant kubernetes as "NAIS"

==Build and release==
developer -> github: git push
github -> ci: Start build
ci -> registry: Push image

==NAIS deploy v1==
ci -> github: Start deployment
note right: Authenticate with GitHub token
github -> hookd: Send webhook to NAIS deploy

==NAIS deploy v2==
ci -> hookd: Start deployment
note right: Authenticate with team API key
hookd -> github: Create deployment

==Deploy phase==
hookd -> deployd: Commission deployment
hookd -> github: Update deployment status
note left: queued
deployd -> kubernetes: Deploy
kubernetes --> deployd
deployd -> hookd: Report status
hookd -> github: Update deployment status
note left: in_progress

loop until timeout or success
	deployd -> kubernetes: Check rollout status
	kubernetes --> deployd
end

deployd -> hookd: Report status
hookd -> github: Update deployment status
note left: success

==Errors==
hookd -> github: Application failed to start
note left: failure
hookd -> github: Error in deployment request
note left: error
hookd -> github: Internal error in NAIS deploy
note left: error

@enduml
