
Which metrics can we collect from the pipeline?


- hvor lang tid tar det fra utvikleren skriver kode til den er i produksjon
- hvor lenge ligger en commit i en PR eller branch før den blir merget til main?

gitt en deploy:
- HVILKEN commit var den første i diffen mellom denne deployen og den forrige?

@startuml component

actor developer as "Developer"
participant ci
participant build
participant sign
participant release
participant hookd
collections deployd
participant naiserator

developer -> ci
note right: Developer pushes code
ci -> build
note right: time from commit to push\n\
time to start workflow\n\
IS IT POSSIBLE?
build --> ci
note right: time to build

ci -> sign
sign --> ci
note right: time to sign

ci -> release
release --> ci
note right: time to release

ci -> hookd
hookd -> deployd
deployd -> naiserator

naiserator --> deployd
deployd --> hookd
note right: time to start deploy
hookd --> ci

deployd --> hookd
note right: time to persist resources
hookd --> ci

deployd --> hookd
note right: time to complete deploy

hookd --> ci
ci --> developer

@enduml
