name: "Nais deploy"
description: "Deploy to a Nais cluster using nais CLI with handlebars templating support"
author: "@nais"

branding:
  color: purple
  icon: zap

runs:
  using: "composite"
  steps:
    - name: Setup nais CLI
      uses: nais/setup@688b8fc05d8b3cbe5b9d17d579efc8db302cf274 # ratchet:nais/setup@v1.0.0-next.7
      with:
        team: ${{ env.TEAM || '' }}
        environment: ${{ env.CLUSTER || '' }}

    - name: Template and deploy
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
