# canary release
#
# this is an application which reports how long it took to deploy.

---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/skipDeploymentMessage: "true"
  labels:
    team: "{{ namespace }}"
  name: nais-deploy-canary
  namespace: "{{ namespace }}"
spec:
  env:
    - name: DEPLOY_START
      value: "{{ now }}"
  image: europe-north1-docker.pkg.dev/nais-io/nais/images/testapp:2023.5.11-2cbaba9
  liveness:
    path: /ping
  port: 8080
  readiness:
    path: /ping
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /metrics
  skipCaBundle: true
