// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"

	"github.com/nais/deploy/pkg/hookd/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockApiKeyStore creates a new instance of MockApiKeyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiKeyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiKeyStore {
	mock := &MockApiKeyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApiKeyStore is an autogenerated mock type for the ApiKeyStore type
type MockApiKeyStore struct {
	mock.Mock
}

type MockApiKeyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiKeyStore) EXPECT() *MockApiKeyStore_Expecter {
	return &MockApiKeyStore_Expecter{mock: &_m.Mock}
}

// ApiKeys provides a mock function for the type MockApiKeyStore
func (_mock *MockApiKeyStore) ApiKeys(ctx context.Context, id string) (ApiKeys, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ApiKeys")
	}

	var r0 ApiKeys
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ApiKeys, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ApiKeys); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ApiKeys)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockApiKeyStore_ApiKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApiKeys'
type MockApiKeyStore_ApiKeys_Call struct {
	*mock.Call
}

// ApiKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockApiKeyStore_Expecter) ApiKeys(ctx any, id any) *MockApiKeyStore_ApiKeys_Call {
	return &MockApiKeyStore_ApiKeys_Call{Call: _e.mock.On("ApiKeys", ctx, id)}
}

func (_c *MockApiKeyStore_ApiKeys_Call) Run(run func(ctx context.Context, id string)) *MockApiKeyStore_ApiKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockApiKeyStore_ApiKeys_Call) Return(apiKeys ApiKeys, err error) *MockApiKeyStore_ApiKeys_Call {
	_c.Call.Return(apiKeys, err)
	return _c
}

func (_c *MockApiKeyStore_ApiKeys_Call) RunAndReturn(run func(ctx context.Context, id string) (ApiKeys, error)) *MockApiKeyStore_ApiKeys_Call {
	_c.Call.Return(run)
	return _c
}

// RotateApiKey provides a mock function for the type MockApiKeyStore
func (_mock *MockApiKeyStore) RotateApiKey(ctx context.Context, team string, key api_v1.Key) error {
	ret := _mock.Called(ctx, team, key)

	if len(ret) == 0 {
		panic("no return value specified for RotateApiKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, api_v1.Key) error); ok {
		r0 = returnFunc(ctx, team, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockApiKeyStore_RotateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateApiKey'
type MockApiKeyStore_RotateApiKey_Call struct {
	*mock.Call
}

// RotateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - team string
//   - key api_v1.Key
func (_e *MockApiKeyStore_Expecter) RotateApiKey(ctx any, team any, key any) *MockApiKeyStore_RotateApiKey_Call {
	return &MockApiKeyStore_RotateApiKey_Call{Call: _e.mock.On("RotateApiKey", ctx, team, key)}
}

func (_c *MockApiKeyStore_RotateApiKey_Call) Run(run func(ctx context.Context, team string, key api_v1.Key)) *MockApiKeyStore_RotateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 api_v1.Key
		if args[2] != nil {
			arg2 = args[2].(api_v1.Key)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockApiKeyStore_RotateApiKey_Call) Return(err error) *MockApiKeyStore_RotateApiKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockApiKeyStore_RotateApiKey_Call) RunAndReturn(run func(ctx context.Context, team string, key api_v1.Key) error) *MockApiKeyStore_RotateApiKey_Call {
	_c.Call.Return(run)
	return _c
}
