// Code generated by mockery v2.6.0. DO NOT EDIT.

package database

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepositoryTeamStore is an autogenerated mock type for the RepositoryTeamStore type
type MockRepositoryTeamStore struct {
	mock.Mock
}

// ReadRepositoryTeams provides a mock function with given fields: ctx, repository
func (_m *MockRepositoryTeamStore) ReadRepositoryTeams(ctx context.Context, repository string) ([]string, error) {
	ret := _m.Called(ctx, repository)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, repository)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteRepositoryTeams provides a mock function with given fields: ctx, repository, teams
func (_m *MockRepositoryTeamStore) WriteRepositoryTeams(ctx context.Context, repository string, teams []string) error {
	ret := _m.Called(ctx, repository, teams)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, repository, teams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
