// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeploymentStore creates a new instance of MockDeploymentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploymentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploymentStore {
	mock := &MockDeploymentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploymentStore is an autogenerated mock type for the DeploymentStore type
type MockDeploymentStore struct {
	mock.Mock
}

type MockDeploymentStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploymentStore) EXPECT() *MockDeploymentStore_Expecter {
	return &MockDeploymentStore_Expecter{mock: &_m.Mock}
}

// Deployment provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) Deployment(ctx context.Context, id string) (*Deployment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Deployment")
	}

	var r0 *Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Deployment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Deployment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentStore_Deployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployment'
type MockDeploymentStore_Deployment_Call struct {
	*mock.Call
}

// Deployment is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockDeploymentStore_Expecter) Deployment(ctx any, id any) *MockDeploymentStore_Deployment_Call {
	return &MockDeploymentStore_Deployment_Call{Call: _e.mock.On("Deployment", ctx, id)}
}

func (_c *MockDeploymentStore_Deployment_Call) Run(run func(ctx context.Context, id string)) *MockDeploymentStore_Deployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_Deployment_Call) Return(deployment *Deployment, err error) *MockDeploymentStore_Deployment_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *MockDeploymentStore_Deployment_Call) RunAndReturn(run func(ctx context.Context, id string) (*Deployment, error)) *MockDeploymentStore_Deployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeploymentResources provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) DeploymentResources(ctx context.Context, deploymentID string) ([]DeploymentResource, error) {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeploymentResources")
	}

	var r0 []DeploymentResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]DeploymentResource, error)); ok {
		return returnFunc(ctx, deploymentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []DeploymentResource); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DeploymentResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentStore_DeploymentResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeploymentResources'
type MockDeploymentStore_DeploymentResources_Call struct {
	*mock.Call
}

// DeploymentResources is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *MockDeploymentStore_Expecter) DeploymentResources(ctx any, deploymentID any) *MockDeploymentStore_DeploymentResources_Call {
	return &MockDeploymentStore_DeploymentResources_Call{Call: _e.mock.On("DeploymentResources", ctx, deploymentID)}
}

func (_c *MockDeploymentStore_DeploymentResources_Call) Run(run func(ctx context.Context, deploymentID string)) *MockDeploymentStore_DeploymentResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_DeploymentResources_Call) Return(deploymentResources []DeploymentResource, err error) *MockDeploymentStore_DeploymentResources_Call {
	_c.Call.Return(deploymentResources, err)
	return _c
}

func (_c *MockDeploymentStore_DeploymentResources_Call) RunAndReturn(run func(ctx context.Context, deploymentID string) ([]DeploymentResource, error)) *MockDeploymentStore_DeploymentResources_Call {
	_c.Call.Return(run)
	return _c
}

// DeploymentStatus provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) DeploymentStatus(ctx context.Context, deploymentID string) ([]DeploymentStatus, error) {
	ret := _mock.Called(ctx, deploymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeploymentStatus")
	}

	var r0 []DeploymentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]DeploymentStatus, error)); ok {
		return returnFunc(ctx, deploymentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []DeploymentStatus); ok {
		r0 = returnFunc(ctx, deploymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]DeploymentStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deploymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentStore_DeploymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeploymentStatus'
type MockDeploymentStore_DeploymentStatus_Call struct {
	*mock.Call
}

// DeploymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - deploymentID string
func (_e *MockDeploymentStore_Expecter) DeploymentStatus(ctx any, deploymentID any) *MockDeploymentStore_DeploymentStatus_Call {
	return &MockDeploymentStore_DeploymentStatus_Call{Call: _e.mock.On("DeploymentStatus", ctx, deploymentID)}
}

func (_c *MockDeploymentStore_DeploymentStatus_Call) Run(run func(ctx context.Context, deploymentID string)) *MockDeploymentStore_DeploymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_DeploymentStatus_Call) Return(deploymentStatuss []DeploymentStatus, err error) *MockDeploymentStore_DeploymentStatus_Call {
	_c.Call.Return(deploymentStatuss, err)
	return _c
}

func (_c *MockDeploymentStore_DeploymentStatus_Call) RunAndReturn(run func(ctx context.Context, deploymentID string) ([]DeploymentStatus, error)) *MockDeploymentStore_DeploymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Deployments provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) Deployments(ctx context.Context, teams []string, clusters []string, ignoreTeams []string, limit int) ([]*Deployment, error) {
	ret := _mock.Called(ctx, teams, clusters, ignoreTeams, limit)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 []*Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, []string, int) ([]*Deployment, error)); ok {
		return returnFunc(ctx, teams, clusters, ignoreTeams, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string, []string, int) []*Deployment); ok {
		r0 = returnFunc(ctx, teams, clusters, ignoreTeams, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, []string, []string, int) error); ok {
		r1 = returnFunc(ctx, teams, clusters, ignoreTeams, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentStore_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type MockDeploymentStore_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - ctx context.Context
//   - teams []string
//   - clusters []string
//   - ignoreTeams []string
//   - limit int
func (_e *MockDeploymentStore_Expecter) Deployments(ctx any, teams any, clusters any, ignoreTeams any, limit any) *MockDeploymentStore_Deployments_Call {
	return &MockDeploymentStore_Deployments_Call{Call: _e.mock.On("Deployments", ctx, teams, clusters, ignoreTeams, limit)}
}

func (_c *MockDeploymentStore_Deployments_Call) Run(run func(ctx context.Context, teams []string, clusters []string, ignoreTeams []string, limit int)) *MockDeploymentStore_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_Deployments_Call) Return(deployments []*Deployment, err error) *MockDeploymentStore_Deployments_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *MockDeploymentStore_Deployments_Call) RunAndReturn(run func(ctx context.Context, teams []string, clusters []string, ignoreTeams []string, limit int) ([]*Deployment, error)) *MockDeploymentStore_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// HistoricDeployments provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) HistoricDeployments(ctx context.Context, cluster string, timestamp time.Time) ([]*Deployment, error) {
	ret := _mock.Called(ctx, cluster, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for HistoricDeployments")
	}

	var r0 []*Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*Deployment, error)); ok {
		return returnFunc(ctx, cluster, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []*Deployment); ok {
		r0 = returnFunc(ctx, cluster, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, cluster, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploymentStore_HistoricDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistoricDeployments'
type MockDeploymentStore_HistoricDeployments_Call struct {
	*mock.Call
}

// HistoricDeployments is a helper method to define mock.On call
//   - ctx context.Context
//   - cluster string
//   - timestamp time.Time
func (_e *MockDeploymentStore_Expecter) HistoricDeployments(ctx any, cluster any, timestamp any) *MockDeploymentStore_HistoricDeployments_Call {
	return &MockDeploymentStore_HistoricDeployments_Call{Call: _e.mock.On("HistoricDeployments", ctx, cluster, timestamp)}
}

func (_c *MockDeploymentStore_HistoricDeployments_Call) Run(run func(ctx context.Context, cluster string, timestamp time.Time)) *MockDeploymentStore_HistoricDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_HistoricDeployments_Call) Return(deployments []*Deployment, err error) *MockDeploymentStore_HistoricDeployments_Call {
	_c.Call.Return(deployments, err)
	return _c
}

func (_c *MockDeploymentStore_HistoricDeployments_Call) RunAndReturn(run func(ctx context.Context, cluster string, timestamp time.Time) ([]*Deployment, error)) *MockDeploymentStore_HistoricDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDeployment provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) WriteDeployment(ctx context.Context, deployment Deployment) error {
	ret := _mock.Called(ctx, deployment)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeployment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Deployment) error); ok {
		r0 = returnFunc(ctx, deployment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentStore_WriteDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDeployment'
type MockDeploymentStore_WriteDeployment_Call struct {
	*mock.Call
}

// WriteDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment Deployment
func (_e *MockDeploymentStore_Expecter) WriteDeployment(ctx any, deployment any) *MockDeploymentStore_WriteDeployment_Call {
	return &MockDeploymentStore_WriteDeployment_Call{Call: _e.mock.On("WriteDeployment", ctx, deployment)}
}

func (_c *MockDeploymentStore_WriteDeployment_Call) Run(run func(ctx context.Context, deployment Deployment)) *MockDeploymentStore_WriteDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Deployment
		if args[1] != nil {
			arg1 = args[1].(Deployment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_WriteDeployment_Call) Return(err error) *MockDeploymentStore_WriteDeployment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentStore_WriteDeployment_Call) RunAndReturn(run func(ctx context.Context, deployment Deployment) error) *MockDeploymentStore_WriteDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDeploymentResource provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) WriteDeploymentResource(ctx context.Context, resource DeploymentResource) error {
	ret := _mock.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeploymentResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeploymentResource) error); ok {
		r0 = returnFunc(ctx, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentStore_WriteDeploymentResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDeploymentResource'
type MockDeploymentStore_WriteDeploymentResource_Call struct {
	*mock.Call
}

// WriteDeploymentResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resource DeploymentResource
func (_e *MockDeploymentStore_Expecter) WriteDeploymentResource(ctx any, resource any) *MockDeploymentStore_WriteDeploymentResource_Call {
	return &MockDeploymentStore_WriteDeploymentResource_Call{Call: _e.mock.On("WriteDeploymentResource", ctx, resource)}
}

func (_c *MockDeploymentStore_WriteDeploymentResource_Call) Run(run func(ctx context.Context, resource DeploymentResource)) *MockDeploymentStore_WriteDeploymentResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeploymentResource
		if args[1] != nil {
			arg1 = args[1].(DeploymentResource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_WriteDeploymentResource_Call) Return(err error) *MockDeploymentStore_WriteDeploymentResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentStore_WriteDeploymentResource_Call) RunAndReturn(run func(ctx context.Context, resource DeploymentResource) error) *MockDeploymentStore_WriteDeploymentResource_Call {
	_c.Call.Return(run)
	return _c
}

// WriteDeploymentStatus provides a mock function for the type MockDeploymentStore
func (_mock *MockDeploymentStore) WriteDeploymentStatus(ctx context.Context, status DeploymentStatus) error {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeploymentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeploymentStatus) error); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploymentStore_WriteDeploymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteDeploymentStatus'
type MockDeploymentStore_WriteDeploymentStatus_Call struct {
	*mock.Call
}

// WriteDeploymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status DeploymentStatus
func (_e *MockDeploymentStore_Expecter) WriteDeploymentStatus(ctx any, status any) *MockDeploymentStore_WriteDeploymentStatus_Call {
	return &MockDeploymentStore_WriteDeploymentStatus_Call{Call: _e.mock.On("WriteDeploymentStatus", ctx, status)}
}

func (_c *MockDeploymentStore_WriteDeploymentStatus_Call) Run(run func(ctx context.Context, status DeploymentStatus)) *MockDeploymentStore_WriteDeploymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(DeploymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeploymentStore_WriteDeploymentStatus_Call) Return(err error) *MockDeploymentStore_WriteDeploymentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploymentStore_WriteDeploymentStatus_Call) RunAndReturn(run func(ctx context.Context, status DeploymentStatus) error) *MockDeploymentStore_WriteDeploymentStatus_Call {
	_c.Call.Return(run)
	return _c
}
