// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package database

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryTeamStore creates a new instance of MockRepositoryTeamStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryTeamStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryTeamStore {
	mock := &MockRepositoryTeamStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryTeamStore is an autogenerated mock type for the RepositoryTeamStore type
type MockRepositoryTeamStore struct {
	mock.Mock
}

type MockRepositoryTeamStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryTeamStore) EXPECT() *MockRepositoryTeamStore_Expecter {
	return &MockRepositoryTeamStore_Expecter{mock: &_m.Mock}
}

// ReadRepositoryTeams provides a mock function for the type MockRepositoryTeamStore
func (_mock *MockRepositoryTeamStore) ReadRepositoryTeams(ctx context.Context, repository string) ([]string, error) {
	ret := _mock.Called(ctx, repository)

	if len(ret) == 0 {
		panic("no return value specified for ReadRepositoryTeams")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, repository)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, repository)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repository)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryTeamStore_ReadRepositoryTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadRepositoryTeams'
type MockRepositoryTeamStore_ReadRepositoryTeams_Call struct {
	*mock.Call
}

// ReadRepositoryTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
func (_e *MockRepositoryTeamStore_Expecter) ReadRepositoryTeams(ctx any, repository any) *MockRepositoryTeamStore_ReadRepositoryTeams_Call {
	return &MockRepositoryTeamStore_ReadRepositoryTeams_Call{Call: _e.mock.On("ReadRepositoryTeams", ctx, repository)}
}

func (_c *MockRepositoryTeamStore_ReadRepositoryTeams_Call) Run(run func(ctx context.Context, repository string)) *MockRepositoryTeamStore_ReadRepositoryTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepositoryTeamStore_ReadRepositoryTeams_Call) Return(strings []string, err error) *MockRepositoryTeamStore_ReadRepositoryTeams_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepositoryTeamStore_ReadRepositoryTeams_Call) RunAndReturn(run func(ctx context.Context, repository string) ([]string, error)) *MockRepositoryTeamStore_ReadRepositoryTeams_Call {
	_c.Call.Return(run)
	return _c
}

// WriteRepositoryTeams provides a mock function for the type MockRepositoryTeamStore
func (_mock *MockRepositoryTeamStore) WriteRepositoryTeams(ctx context.Context, repository string, teams []string) error {
	ret := _mock.Called(ctx, repository, teams)

	if len(ret) == 0 {
		panic("no return value specified for WriteRepositoryTeams")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, repository, teams)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryTeamStore_WriteRepositoryTeams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteRepositoryTeams'
type MockRepositoryTeamStore_WriteRepositoryTeams_Call struct {
	*mock.Call
}

// WriteRepositoryTeams is a helper method to define mock.On call
//   - ctx context.Context
//   - repository string
//   - teams []string
func (_e *MockRepositoryTeamStore_Expecter) WriteRepositoryTeams(ctx any, repository any, teams any) *MockRepositoryTeamStore_WriteRepositoryTeams_Call {
	return &MockRepositoryTeamStore_WriteRepositoryTeams_Call{Call: _e.mock.On("WriteRepositoryTeams", ctx, repository, teams)}
}

func (_c *MockRepositoryTeamStore_WriteRepositoryTeams_Call) Run(run func(ctx context.Context, repository string, teams []string)) *MockRepositoryTeamStore_WriteRepositoryTeams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepositoryTeamStore_WriteRepositoryTeams_Call) Return(err error) *MockRepositoryTeamStore_WriteRepositoryTeams_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryTeamStore_WriteRepositoryTeams_Call) RunAndReturn(run func(ctx context.Context, repository string, teams []string) error) *MockRepositoryTeamStore_WriteRepositoryTeams_Call {
	_c.Call.Return(run)
	return _c
}
