apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: {{ include "hookd.name" . }}
  labels:
    {{- include "hookd.labels" . | nindent 4 }}
stringData:
{{- if .Values.database.encryptionKey }}
  HOOKD_DATABASE_ENCRYPTION_KEY: "{{ .Values.database.encryptionKey }}"
{{- end }}
  HOOKD_BASE_URL: "https://{{ .Values.ingress.host  }}"
  HOOKD_DATABASE_URL: "postgres://{{ .Values.database.user }}@127.0.0.1:5432/{{ .Values.database.name }}?sslmode=disable"
  HOOKD_DEPLOYD_KEYS: '{{ .Values.deploydPreSharedKeys }}'
  HOOKD_FRONTEND_KEYS: "{{ .Values.frontendPreSharedKey }}"
  HOOKD_GOOGLE_CLIENT_ID: "{{ .Values.googleClient.id }}"
  HOOKD_GOOGLE_CLUSTER_PROJECTS: "{{ .Values.googleClusterProjects }}"
  HOOKD_GOOGLE_WELL_KNOWN_URL: "https://accounts.google.com/.well-known/openid-configuration"
  HOOKD_GRPC_ADDRESS: "0.0.0.0:9090"
  HOOKD_GRPC_CLI_AUTHENTICATION: "true"
  HOOKD_GRPC_DEPLOYD_AUTHENTICATION: "true"
  HOOKD_LISTEN_ADDRESS: "0.0.0.0:8080"
  HOOKD_LOG_FORMAT: json
  HOOKD_LOG_LEVEL: info
  HOOKD_LOG_LINK_FORMATTER: "{{ .Values.logLinkFormatter }}"
  HOOKD_OAUTH_ENABLED: "true"
  HOOKD_PROVISION_KEY: "{{ .Values.provisionKey }}"
  HOOKD_NAIS_API_ADDRESS: "{{ .Values.naisAPI.address }}"
  HOOKD_NAIS_API_INSECURE_CONNECTION: "{{ .Values.naisAPI.insecureConnection }}"
