// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/deployment.proto

package deployment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GithubDeploymentState int32

const (
	GithubDeploymentState_success     GithubDeploymentState = 0
	GithubDeploymentState_error       GithubDeploymentState = 1
	GithubDeploymentState_failure     GithubDeploymentState = 2
	GithubDeploymentState_inactive    GithubDeploymentState = 3
	GithubDeploymentState_in_progress GithubDeploymentState = 4
	GithubDeploymentState_queued      GithubDeploymentState = 5
	GithubDeploymentState_pending     GithubDeploymentState = 6
)

var GithubDeploymentState_name = map[int32]string{
	0: "success",
	1: "error",
	2: "failure",
	3: "inactive",
	4: "in_progress",
	5: "queued",
	6: "pending",
}

var GithubDeploymentState_value = map[string]int32{
	"success":     0,
	"error":       1,
	"failure":     2,
	"inactive":    3,
	"in_progress": 4,
	"queued":      5,
	"pending":     6,
}

func (x GithubDeploymentState) String() string {
	return proto.EnumName(GithubDeploymentState_name, int32(x))
}

func (GithubDeploymentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{0}
}

type GithubRepository struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepository) Reset()         { *m = GithubRepository{} }
func (m *GithubRepository) String() string { return proto.CompactTextString(m) }
func (*GithubRepository) ProtoMessage()    {}
func (*GithubRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{0}
}

func (m *GithubRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepository.Unmarshal(m, b)
}
func (m *GithubRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepository.Marshal(b, m, deterministic)
}
func (m *GithubRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepository.Merge(m, src)
}
func (m *GithubRepository) XXX_Size() int {
	return xxx_messageInfo_GithubRepository.Size(m)
}
func (m *GithubRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepository.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepository proto.InternalMessageInfo

func (m *GithubRepository) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GithubRepository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeploymentSpec struct {
	Repository           *GithubRepository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	DeploymentID         int64             `protobuf:"varint,2,opt,name=deploymentID,proto3" json:"deploymentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentSpec) Reset()         { *m = DeploymentSpec{} }
func (m *DeploymentSpec) String() string { return proto.CompactTextString(m) }
func (*DeploymentSpec) ProtoMessage()    {}
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{1}
}

func (m *DeploymentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentSpec.Unmarshal(m, b)
}
func (m *DeploymentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentSpec.Marshal(b, m, deterministic)
}
func (m *DeploymentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentSpec.Merge(m, src)
}
func (m *DeploymentSpec) XXX_Size() int {
	return xxx_messageInfo_DeploymentSpec.Size(m)
}
func (m *DeploymentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentSpec proto.InternalMessageInfo

func (m *DeploymentSpec) GetRepository() *GithubRepository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *DeploymentSpec) GetDeploymentID() int64 {
	if m != nil {
		return m.DeploymentID
	}
	return 0
}

type Kubernetes struct {
	Resources            []*_struct.Struct `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{2}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetResources() []*_struct.Struct {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Payload struct {
	Version              []int32     `protobuf:"varint,1,rep,packed,name=version,proto3" json:"version,omitempty"`
	Team                 string      `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Kubernetes           *Kubernetes `protobuf:"bytes,3,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() []int32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Payload) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Payload) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

type DeploymentRequest struct {
	Deployment           *DeploymentSpec `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Timestamp            int64           `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Deadline             int64           `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Cluster              string          `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DeliveryID           string          `protobuf:"bytes,6,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	PayloadSpec          *Payload        `protobuf:"bytes,7,opt,name=payloadSpec,proto3" json:"payloadSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DeploymentRequest) Reset()         { *m = DeploymentRequest{} }
func (m *DeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*DeploymentRequest) ProtoMessage()    {}
func (*DeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{4}
}

func (m *DeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRequest.Unmarshal(m, b)
}
func (m *DeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRequest.Marshal(b, m, deterministic)
}
func (m *DeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRequest.Merge(m, src)
}
func (m *DeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_DeploymentRequest.Size(m)
}
func (m *DeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRequest proto.InternalMessageInfo

func (m *DeploymentRequest) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *DeploymentRequest) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *DeploymentRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeploymentRequest) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

func (m *DeploymentRequest) GetPayloadSpec() *Payload {
	if m != nil {
		return m.PayloadSpec
	}
	return nil
}

type DeploymentStatus struct {
	Deployment           *DeploymentSpec       `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	State                GithubDeploymentState `protobuf:"varint,2,opt,name=state,proto3,enum=deployment.GithubDeploymentState" json:"state,omitempty"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DeliveryID           string                `protobuf:"bytes,4,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeploymentStatus) Reset()         { *m = DeploymentStatus{} }
func (m *DeploymentStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatus) ProtoMessage()    {}
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{5}
}

func (m *DeploymentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatus.Unmarshal(m, b)
}
func (m *DeploymentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatus.Merge(m, src)
}
func (m *DeploymentStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatus.Size(m)
}
func (m *DeploymentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatus proto.InternalMessageInfo

func (m *DeploymentStatus) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentStatus) GetState() GithubDeploymentState {
	if m != nil {
		return m.State
	}
	return GithubDeploymentState_success
}

func (m *DeploymentStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeploymentStatus) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

type SignedMessage struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f728dae8917e37ee, []int{6}
}

func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("deployment.GithubDeploymentState", GithubDeploymentState_name, GithubDeploymentState_value)
	proto.RegisterType((*GithubRepository)(nil), "deployment.GithubRepository")
	proto.RegisterType((*DeploymentSpec)(nil), "deployment.DeploymentSpec")
	proto.RegisterType((*Kubernetes)(nil), "deployment.Kubernetes")
	proto.RegisterType((*Payload)(nil), "deployment.Payload")
	proto.RegisterType((*DeploymentRequest)(nil), "deployment.DeploymentRequest")
	proto.RegisterType((*DeploymentStatus)(nil), "deployment.DeploymentStatus")
	proto.RegisterType((*SignedMessage)(nil), "deployment.SignedMessage")
}

func init() { proto.RegisterFile("protobuf/deployment.proto", fileDescriptor_f728dae8917e37ee) }

var fileDescriptor_f728dae8917e37ee = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0x4b, 0xd3, 0xae, 0x37, 0x65, 0x04, 0xf3, 0x15, 0xa6, 0x0a, 0x95, 0x3c, 0x4d, 0x3c,
	0x74, 0x52, 0xd1, 0x40, 0x42, 0x7b, 0xa3, 0xd2, 0x34, 0x10, 0x12, 0x72, 0x7f, 0x00, 0x72, 0x93,
	0xbb, 0x60, 0x91, 0xd8, 0x99, 0x3f, 0x8a, 0xfa, 0x13, 0xf8, 0x69, 0xfc, 0x2b, 0x14, 0xa7, 0x6d,
	0xdc, 0xc2, 0x1b, 0x6f, 0xbe, 0x27, 0xc7, 0xf7, 0x9e, 0x73, 0xae, 0x03, 0x2f, 0x6b, 0x25, 0x8d,
	0x5c, 0xd9, 0xbb, 0xcb, 0x1c, 0xeb, 0x52, 0x6e, 0x2a, 0x14, 0x66, 0xe6, 0x30, 0x02, 0x1d, 0x72,
	0x3e, 0x29, 0xa4, 0x2c, 0x4a, 0xbc, 0xdc, 0xb3, 0xb5, 0x51, 0x36, 0xdb, 0x32, 0xd3, 0x6b, 0x88,
	0x6f, 0xb8, 0xf9, 0x6e, 0x57, 0x14, 0x6b, 0xa9, 0xb9, 0x91, 0x6a, 0x43, 0x9e, 0x42, 0x28, 0x7f,
	0x0a, 0x54, 0x49, 0x6f, 0xda, 0xbb, 0x18, 0xd1, 0xb6, 0x20, 0x04, 0xfa, 0x82, 0x55, 0x98, 0x9c,
	0x38, 0xd0, 0x9d, 0x53, 0x05, 0x67, 0x8b, 0xfd, 0xa4, 0x65, 0x8d, 0x19, 0xb9, 0x06, 0x50, 0xfb,
	0x4e, 0xae, 0x41, 0x34, 0x9f, 0xcc, 0x3c, 0x81, 0xc7, 0xd3, 0xa8, 0xc7, 0x27, 0x29, 0x8c, 0x3b,
	0xea, 0xed, 0xc2, 0xcd, 0x0a, 0xe8, 0x01, 0x96, 0x7e, 0x04, 0xf8, 0x6c, 0x57, 0xa8, 0x04, 0x1a,
	0xd4, 0xe4, 0x0a, 0x46, 0x0a, 0xb5, 0xb4, 0x2a, 0x43, 0x9d, 0xf4, 0xa6, 0xc1, 0x45, 0x34, 0x7f,
	0x31, 0x6b, 0x1d, 0xcf, 0x76, 0x8e, 0x67, 0x4b, 0xe7, 0x98, 0x76, 0xcc, 0x54, 0xc2, 0xf0, 0x2b,
	0xdb, 0x94, 0x92, 0xe5, 0x24, 0x81, 0xe1, 0x1a, 0x95, 0xe6, 0x52, 0xb8, 0xfb, 0x21, 0xdd, 0x95,
	0x8d, 0x63, 0x83, 0xac, 0xda, 0x39, 0x6e, 0xce, 0xe4, 0x1d, 0xc0, 0x8f, 0xfd, 0xf4, 0x24, 0x70,
	0xfe, 0x9e, 0xfb, 0xfe, 0x3a, 0x6d, 0xd4, 0x63, 0xa6, 0xbf, 0x4e, 0xe0, 0x71, 0x17, 0x15, 0xc5,
	0x7b, 0x8b, 0xda, 0x90, 0x0f, 0xe0, 0x6d, 0x6a, 0x9b, 0xd6, 0xb9, 0xdf, 0xed, 0x30, 0x5d, 0xea,
	0xb1, 0xc9, 0x04, 0x46, 0x86, 0x57, 0xa8, 0x0d, 0xab, 0xea, 0x6d, 0x50, 0x1d, 0x40, 0xce, 0xe1,
	0x34, 0x47, 0x96, 0x97, 0x5c, 0xa0, 0x53, 0x19, 0xd0, 0x7d, 0xdd, 0x38, 0xce, 0x4a, 0xab, 0x0d,
	0xaa, 0x24, 0x74, 0xd6, 0x76, 0x25, 0x79, 0xd5, 0xe8, 0x29, 0xf9, 0x1a, 0xd5, 0xe6, 0x76, 0x91,
	0x0c, 0xdc, 0x47, 0x0f, 0x21, 0x57, 0x10, 0xd5, 0x6d, 0x6c, 0x8d, 0x9c, 0x64, 0xe8, 0x04, 0x3f,
	0xf1, 0x05, 0x6f, 0x53, 0xa5, 0x3e, 0xef, 0x53, 0xff, 0xb4, 0x1f, 0x87, 0x74, 0xb8, 0x85, 0xd2,
	0xdf, 0x3d, 0x88, 0x3d, 0x63, 0x86, 0x19, 0xab, 0xff, 0x2b, 0x8a, 0xf7, 0x10, 0x6a, 0xc3, 0x4c,
	0xfb, 0x36, 0xcf, 0xe6, 0xaf, 0xff, 0x7e, 0x6f, 0x87, 0xe3, 0x90, 0xb6, 0x7c, 0x32, 0x85, 0x28,
	0x47, 0x9d, 0x29, 0x5e, 0x9b, 0x66, 0xff, 0x81, 0x33, 0xec, 0x43, 0x47, 0x89, 0xf4, 0x8f, 0x13,
	0x49, 0x6f, 0xe0, 0xe1, 0x92, 0x17, 0x02, 0xf3, 0x2f, 0xa8, 0x35, 0x2b, 0x5c, 0xb8, 0x55, 0x7b,
	0x74, 0x26, 0xc6, 0x74, 0x57, 0x36, 0x0b, 0xd3, 0xbc, 0x10, 0xcc, 0x58, 0xd5, 0x2a, 0x1d, 0xd3,
	0x0e, 0x78, 0x63, 0xe0, 0xd9, 0x3f, 0xa5, 0x92, 0x08, 0x86, 0xda, 0x66, 0x19, 0x6a, 0x1d, 0x3f,
	0x20, 0x23, 0x08, 0x51, 0x29, 0xa9, 0xe2, 0x5e, 0x83, 0xdf, 0x31, 0x5e, 0x5a, 0x85, 0xf1, 0x09,
	0x19, 0xc3, 0x29, 0x17, 0x2c, 0x33, 0x7c, 0x8d, 0x71, 0x40, 0x1e, 0x41, 0xc4, 0xc5, 0xb7, 0x5a,
	0xc9, 0x42, 0x35, 0xd7, 0xfa, 0x04, 0x60, 0x70, 0x6f, 0xd1, 0x62, 0x1e, 0x87, 0xcd, 0xbd, 0x1a,
	0x45, 0xce, 0x45, 0x11, 0x0f, 0x56, 0x03, 0xf7, 0x8f, 0xbc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x04, 0x11, 0xe3, 0xe8, 0x4c, 0x04, 0x00, 0x00,
}
