// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment/deployment.proto

package deployment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GithubDeploymentState int32

const (
	GithubDeploymentState_success     GithubDeploymentState = 0
	GithubDeploymentState_error       GithubDeploymentState = 1
	GithubDeploymentState_failure     GithubDeploymentState = 2
	GithubDeploymentState_inactive    GithubDeploymentState = 3
	GithubDeploymentState_in_progress GithubDeploymentState = 4
	GithubDeploymentState_queued      GithubDeploymentState = 5
	GithubDeploymentState_pending     GithubDeploymentState = 6
)

var GithubDeploymentState_name = map[int32]string{
	0: "success",
	1: "error",
	2: "failure",
	3: "inactive",
	4: "in_progress",
	5: "queued",
	6: "pending",
}

var GithubDeploymentState_value = map[string]int32{
	"success":     0,
	"error":       1,
	"failure":     2,
	"inactive":    3,
	"in_progress": 4,
	"queued":      5,
	"pending":     6,
}

func (x GithubDeploymentState) String() string {
	return proto.EnumName(GithubDeploymentState_name, int32(x))
}

func (GithubDeploymentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{0}
}

type GithubRepository struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepository) Reset()         { *m = GithubRepository{} }
func (m *GithubRepository) String() string { return proto.CompactTextString(m) }
func (*GithubRepository) ProtoMessage()    {}
func (*GithubRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{0}
}

func (m *GithubRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepository.Unmarshal(m, b)
}
func (m *GithubRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepository.Marshal(b, m, deterministic)
}
func (m *GithubRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepository.Merge(m, src)
}
func (m *GithubRepository) XXX_Size() int {
	return xxx_messageInfo_GithubRepository.Size(m)
}
func (m *GithubRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepository.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepository proto.InternalMessageInfo

func (m *GithubRepository) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GithubRepository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeploymentSpec struct {
	Repository           *GithubRepository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	DeploymentID         int64             `protobuf:"varint,2,opt,name=deploymentID,proto3" json:"deploymentID,omitempty"`
	Environment          string            `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Ref                  string            `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentSpec) Reset()         { *m = DeploymentSpec{} }
func (m *DeploymentSpec) String() string { return proto.CompactTextString(m) }
func (*DeploymentSpec) ProtoMessage()    {}
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{1}
}

func (m *DeploymentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentSpec.Unmarshal(m, b)
}
func (m *DeploymentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentSpec.Marshal(b, m, deterministic)
}
func (m *DeploymentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentSpec.Merge(m, src)
}
func (m *DeploymentSpec) XXX_Size() int {
	return xxx_messageInfo_DeploymentSpec.Size(m)
}
func (m *DeploymentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentSpec proto.InternalMessageInfo

func (m *DeploymentSpec) GetRepository() *GithubRepository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *DeploymentSpec) GetDeploymentID() int64 {
	if m != nil {
		return m.DeploymentID
	}
	return 0
}

func (m *DeploymentSpec) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *DeploymentSpec) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Kubernetes struct {
	Resources            []*_struct.Struct `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{2}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetResources() []*_struct.Struct {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Payload struct {
	Version              []int32     `protobuf:"varint,1,rep,packed,name=version,proto3" json:"version,omitempty"`
	Team                 string      `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Kubernetes           *Kubernetes `protobuf:"bytes,3,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() []int32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Payload) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Payload) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

type DeploymentRequest struct {
	Deployment           *DeploymentSpec      `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Deadline             int64                `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Cluster              string               `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DeliveryID           string               `protobuf:"bytes,6,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	PayloadSpec          *Payload             `protobuf:"bytes,7,opt,name=payloadSpec,proto3" json:"payloadSpec,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Status               *DeploymentStatus    `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeploymentRequest) Reset()         { *m = DeploymentRequest{} }
func (m *DeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*DeploymentRequest) ProtoMessage()    {}
func (*DeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{4}
}

func (m *DeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRequest.Unmarshal(m, b)
}
func (m *DeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRequest.Marshal(b, m, deterministic)
}
func (m *DeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRequest.Merge(m, src)
}
func (m *DeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_DeploymentRequest.Size(m)
}
func (m *DeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRequest proto.InternalMessageInfo

func (m *DeploymentRequest) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentRequest) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *DeploymentRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeploymentRequest) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

func (m *DeploymentRequest) GetPayloadSpec() *Payload {
	if m != nil {
		return m.PayloadSpec
	}
	return nil
}

func (m *DeploymentRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *DeploymentRequest) GetStatus() *DeploymentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeploymentStatus struct {
	Deployment           *DeploymentSpec       `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	State                GithubDeploymentState `protobuf:"varint,2,opt,name=state,proto3,enum=deployment.GithubDeploymentState" json:"state,omitempty"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DeliveryID           string                `protobuf:"bytes,4,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	Team                 string                `protobuf:"bytes,5,opt,name=team,proto3" json:"team,omitempty"`
	Cluster              string                `protobuf:"bytes,6,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Time                 *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Id                   string                `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeploymentStatus) Reset()         { *m = DeploymentStatus{} }
func (m *DeploymentStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatus) ProtoMessage()    {}
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{5}
}

func (m *DeploymentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatus.Unmarshal(m, b)
}
func (m *DeploymentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatus.Merge(m, src)
}
func (m *DeploymentStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatus.Size(m)
}
func (m *DeploymentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatus proto.InternalMessageInfo

func (m *DeploymentStatus) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentStatus) GetState() GithubDeploymentState {
	if m != nil {
		return m.State
	}
	return GithubDeploymentState_success
}

func (m *DeploymentStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeploymentStatus) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

func (m *DeploymentStatus) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *DeploymentStatus) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeploymentStatus) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *DeploymentStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SignedMessage struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{6}
}

func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("deployment.GithubDeploymentState", GithubDeploymentState_name, GithubDeploymentState_value)
	proto.RegisterType((*GithubRepository)(nil), "deployment.GithubRepository")
	proto.RegisterType((*DeploymentSpec)(nil), "deployment.DeploymentSpec")
	proto.RegisterType((*Kubernetes)(nil), "deployment.Kubernetes")
	proto.RegisterType((*Payload)(nil), "deployment.Payload")
	proto.RegisterType((*DeploymentRequest)(nil), "deployment.DeploymentRequest")
	proto.RegisterType((*DeploymentStatus)(nil), "deployment.DeploymentStatus")
	proto.RegisterType((*SignedMessage)(nil), "deployment.SignedMessage")
}

func init() {
	proto.RegisterFile("deployment/deployment.proto", fileDescriptor_700de9d3ee114f41)
}

var fileDescriptor_700de9d3ee114f41 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x6d, 0x12, 0x3b, 0x3f, 0x93, 0x7c, 0xfd, 0xcc, 0xf2, 0x67, 0x85, 0x02, 0xc5, 0x57, 0x15,
	0x17, 0x29, 0x0a, 0x14, 0x24, 0xd4, 0x1b, 0xa0, 0x52, 0x69, 0x11, 0x12, 0xda, 0x72, 0x8f, 0x1c,
	0x7b, 0x1a, 0x56, 0x38, 0xbb, 0xee, 0xee, 0x3a, 0x28, 0x2f, 0xc4, 0xb3, 0xf0, 0x1c, 0x3c, 0x09,
	0xda, 0xb5, 0x1d, 0x6f, 0xd2, 0x0a, 0x09, 0x71, 0x37, 0x73, 0xf6, 0xcc, 0xce, 0xec, 0x99, 0xb3,
	0xf0, 0x20, 0xc5, 0x3c, 0x13, 0xab, 0x05, 0x72, 0x7d, 0xd8, 0x84, 0x93, 0x5c, 0x0a, 0x2d, 0x08,
	0x34, 0xc8, 0xf8, 0xf1, 0x5c, 0x88, 0x79, 0x86, 0x87, 0xf6, 0x64, 0x56, 0x5c, 0x1e, 0x6a, 0xb6,
	0x40, 0xa5, 0xe3, 0x45, 0x5e, 0x92, 0xc7, 0x7b, 0xdb, 0x04, 0xa5, 0x65, 0x91, 0x54, 0x57, 0x45,
	0xc7, 0x10, 0x9c, 0x32, 0xfd, 0xb5, 0x98, 0x51, 0xcc, 0x85, 0x62, 0x5a, 0xc8, 0x15, 0xb9, 0x03,
	0xbe, 0xf8, 0xce, 0x51, 0x86, 0xad, 0xfd, 0xd6, 0xc1, 0x80, 0x96, 0x09, 0x21, 0xe0, 0xf1, 0x78,
	0x81, 0x61, 0xdb, 0x82, 0x36, 0x8e, 0x7e, 0xb4, 0x60, 0xf7, 0x64, 0x3d, 0xcb, 0x45, 0x8e, 0x09,
	0x39, 0x06, 0x90, 0xeb, 0xab, 0xec, 0x0d, 0xc3, 0xe9, 0xde, 0xc4, 0x79, 0xc2, 0x76, 0x3b, 0xea,
	0xf0, 0x49, 0x04, 0xa3, 0x86, 0x7a, 0x76, 0x62, 0x9b, 0x75, 0xe8, 0x06, 0x46, 0xf6, 0x61, 0x88,
	0x7c, 0xc9, 0xa4, 0xe0, 0x06, 0x08, 0x3b, 0x76, 0x1e, 0x17, 0x22, 0x01, 0x74, 0x24, 0x5e, 0x86,
	0x9e, 0x3d, 0x31, 0x61, 0xf4, 0x0e, 0xe0, 0x43, 0x31, 0x43, 0xc9, 0x51, 0xa3, 0x22, 0x47, 0x30,
	0x90, 0xa8, 0x44, 0x21, 0x13, 0x54, 0x61, 0x6b, 0xbf, 0x73, 0x30, 0x9c, 0xde, 0x9f, 0x94, 0x32,
	0x4d, 0x6a, 0x99, 0x26, 0x17, 0x56, 0x26, 0xda, 0x30, 0x23, 0x01, 0xbd, 0x4f, 0xf1, 0x2a, 0x13,
	0x71, 0x4a, 0x42, 0xe8, 0x2d, 0x51, 0x2a, 0x26, 0xb8, 0xad, 0xf7, 0x69, 0x9d, 0x1a, 0x99, 0x34,
	0xc6, 0x8b, 0x5a, 0x26, 0x13, 0x93, 0x97, 0x00, 0xdf, 0xd6, 0xdd, 0xed, 0xc0, 0xc3, 0xe9, 0x3d,
	0x57, 0x93, 0x66, 0x36, 0xea, 0x30, 0xa3, 0x5f, 0x6d, 0xb8, 0xd5, 0xc8, 0x4b, 0xf1, 0xaa, 0x40,
	0xa5, 0xc9, 0x6b, 0x70, 0xf6, 0x5f, 0x29, 0x3c, 0x76, 0x6f, 0xdb, 0xdc, 0x08, 0x75, 0xd8, 0x64,
	0x0c, 0xfd, 0x14, 0xe3, 0x34, 0x63, 0x1c, 0xed, 0x1c, 0x1d, 0xba, 0xce, 0xcd, 0x9b, 0x92, 0xac,
	0x50, 0x1a, 0x65, 0xe8, 0xdb, 0xe1, 0xeb, 0x94, 0x3c, 0x32, 0x1d, 0x33, 0xb6, 0x44, 0xb9, 0x3a,
	0x3b, 0x09, 0xbb, 0xf6, 0xd0, 0x41, 0xc8, 0x11, 0x0c, 0xf3, 0x52, 0x18, 0xd3, 0x30, 0xec, 0xd9,
	0x91, 0x6e, 0xbb, 0x23, 0x55, 0xba, 0x51, 0x97, 0x47, 0x26, 0xe0, 0x19, 0xb3, 0x86, 0xfd, 0xea,
	0x09, 0xdb, 0x1b, 0xf8, 0x5c, 0x3b, 0x99, 0x5a, 0x1e, 0x79, 0x01, 0x5d, 0xa5, 0x63, 0x5d, 0xa8,
	0x70, 0x70, 0xdd, 0x56, 0xce, 0xa3, 0x2d, 0x87, 0x56, 0xdc, 0x73, 0xaf, 0xdf, 0x0e, 0x3a, 0xe7,
	0x5e, 0xdf, 0x0b, 0x7c, 0x3a, 0x58, 0x7f, 0x0e, 0xda, 0xab, 0x26, 0x89, 0x7e, 0xb6, 0x21, 0xd8,
	0x2e, 0xfe, 0x27, 0x8d, 0x5f, 0x81, 0x6f, 0x5a, 0x97, 0x3f, 0x65, 0x77, 0xfa, 0xe4, 0xba, 0xf9,
	0x37, 0xdb, 0x21, 0x2d, 0xf9, 0xc6, 0xd8, 0x29, 0xaa, 0x44, 0xb2, 0x5c, 0x1b, 0x63, 0x55, 0xc6,
	0x76, 0xa0, 0xad, 0x45, 0x78, 0xd7, 0x16, 0x51, 0x9b, 0xcf, 0x77, 0xcc, 0xe7, 0xac, 0xb5, 0xbb,
	0xb9, 0xd6, 0xbf, 0xd5, 0x7f, 0x17, 0xda, 0x2c, 0xb5, 0xda, 0x0f, 0x68, 0x9b, 0xa5, 0xe7, 0x5e,
	0xbf, 0x17, 0xf4, 0x1d, 0x4d, 0xa3, 0x53, 0xf8, 0xef, 0x82, 0xcd, 0x39, 0xa6, 0x1f, 0x51, 0xa9,
	0x78, 0x6e, 0x2d, 0xb5, 0x28, 0x43, 0xab, 0xe1, 0x88, 0xd6, 0x29, 0xd9, 0x83, 0x81, 0x62, 0x73,
	0x1e, 0xeb, 0x42, 0x96, 0x42, 0x8d, 0x68, 0x03, 0x3c, 0xd5, 0x70, 0xf7, 0x46, 0xa5, 0xc8, 0x10,
	0x7a, 0xaa, 0x48, 0x12, 0x54, 0x2a, 0xd8, 0x21, 0x03, 0xf0, 0x51, 0x4a, 0x21, 0x83, 0x96, 0xc1,
	0x2f, 0x63, 0x96, 0x15, 0x12, 0x83, 0x36, 0x19, 0x41, 0x9f, 0xf1, 0x38, 0xd1, 0x6c, 0x89, 0x41,
	0x87, 0xfc, 0x0f, 0x43, 0xc6, 0xbf, 0xe4, 0x52, 0xcc, 0xa5, 0x29, 0xf3, 0x08, 0x40, 0xf7, 0xaa,
	0xc0, 0x02, 0xd3, 0xc0, 0x37, 0x75, 0x39, 0xf2, 0x94, 0xf1, 0x79, 0xd0, 0x9d, 0x52, 0xe8, 0x96,
	0xfd, 0xc8, 0x7b, 0xf0, 0xdf, 0xe4, 0x79, 0xb6, 0x22, 0x0f, 0x6f, 0xde, 0x79, 0xf5, 0x15, 0xc7,
	0x7f, 0x74, 0x60, 0xb4, 0xf3, 0xac, 0xf5, 0x76, 0x0c, 0x21, 0x17, 0x13, 0x1e, 0x2f, 0x4b, 0x59,
	0x95, 0x53, 0x30, 0xeb, 0x5a, 0xe8, 0xf9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xa9, 0xdc,
	0x6e, 0xec, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeployClient is the client API for Deploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployClient interface {
	Apply(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (Deploy_ApplyClient, error)
}

type deployClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployClient(cc grpc.ClientConnInterface) DeployClient {
	return &deployClient{cc}
}

func (c *deployClient) Apply(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (Deploy_ApplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Deploy_serviceDesc.Streams[0], "/deployment.Deploy/Apply", opts...)
	if err != nil {
		return nil, err
	}
	x := &deployApplyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Deploy_ApplyClient interface {
	Recv() (*DeploymentStatus, error)
	grpc.ClientStream
}

type deployApplyClient struct {
	grpc.ClientStream
}

func (x *deployApplyClient) Recv() (*DeploymentStatus, error) {
	m := new(DeploymentStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DeployServer is the server API for Deploy service.
type DeployServer interface {
	Apply(*DeploymentRequest, Deploy_ApplyServer) error
}

// UnimplementedDeployServer can be embedded to have forward compatible implementations.
type UnimplementedDeployServer struct {
}

func (*UnimplementedDeployServer) Apply(req *DeploymentRequest, srv Deploy_ApplyServer) error {
	return status.Errorf(codes.Unimplemented, "method Apply not implemented")
}

func RegisterDeployServer(s *grpc.Server, srv DeployServer) {
	s.RegisterService(&_Deploy_serviceDesc, srv)
}

func _Deploy_Apply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeploymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServer).Apply(m, &deployApplyServer{stream})
}

type Deploy_ApplyServer interface {
	Send(*DeploymentStatus) error
	grpc.ServerStream
}

type deployApplyServer struct {
	grpc.ServerStream
}

func (x *deployApplyServer) Send(m *DeploymentStatus) error {
	return x.ServerStream.SendMsg(m)
}

var _Deploy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deployment.Deploy",
	HandlerType: (*DeployServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Apply",
			Handler:       _Deploy_Apply_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployment/deployment.proto",
}
