// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dispatchserver

import (
	"context"

	"github.com/nais/deploy/pkg/pb"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockDispatchServer creates a new instance of MockDispatchServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatchServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatchServer {
	mock := &MockDispatchServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatchServer is an autogenerated mock type for the DispatchServer type
type MockDispatchServer struct {
	mock.Mock
}

type MockDispatchServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatchServer) EXPECT() *MockDispatchServer_Expecter {
	return &MockDispatchServer_Expecter{mock: &_m.Mock}
}

// Deployments provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) Deployments(getDeploymentOpts *pb.GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[pb.DeploymentRequest]) error {
	ret := _mock.Called(getDeploymentOpts, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*pb.GetDeploymentOpts, grpc.ServerStreamingServer[pb.DeploymentRequest]) error); ok {
		r0 = returnFunc(getDeploymentOpts, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatchServer_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type MockDispatchServer_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - getDeploymentOpts *pb.GetDeploymentOpts
//   - serverStreamingServer grpc.ServerStreamingServer[pb.DeploymentRequest]
func (_e *MockDispatchServer_Expecter) Deployments(getDeploymentOpts any, serverStreamingServer any) *MockDispatchServer_Deployments_Call {
	return &MockDispatchServer_Deployments_Call{Call: _e.mock.On("Deployments", getDeploymentOpts, serverStreamingServer)}
}

func (_c *MockDispatchServer_Deployments_Call) Run(run func(getDeploymentOpts *pb.GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[pb.DeploymentRequest])) *MockDispatchServer_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *pb.GetDeploymentOpts
		if args[0] != nil {
			arg0 = args[0].(*pb.GetDeploymentOpts)
		}
		var arg1 grpc.ServerStreamingServer[pb.DeploymentRequest]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[pb.DeploymentRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_Deployments_Call) Return(err error) *MockDispatchServer_Deployments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatchServer_Deployments_Call) RunAndReturn(run func(getDeploymentOpts *pb.GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[pb.DeploymentRequest]) error) *MockDispatchServer_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// HandleDeploymentStatus provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) HandleDeploymentStatus(ctx context.Context, status *pb.DeploymentStatus) error {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for HandleDeploymentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeploymentStatus) error); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatchServer_HandleDeploymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDeploymentStatus'
type MockDispatchServer_HandleDeploymentStatus_Call struct {
	*mock.Call
}

// HandleDeploymentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status *pb.DeploymentStatus
func (_e *MockDispatchServer_Expecter) HandleDeploymentStatus(ctx any, status any) *MockDispatchServer_HandleDeploymentStatus_Call {
	return &MockDispatchServer_HandleDeploymentStatus_Call{Call: _e.mock.On("HandleDeploymentStatus", ctx, status)}
}

func (_c *MockDispatchServer_HandleDeploymentStatus_Call) Run(run func(ctx context.Context, status *pb.DeploymentStatus)) *MockDispatchServer_HandleDeploymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(*pb.DeploymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_HandleDeploymentStatus_Call) Return(err error) *MockDispatchServer_HandleDeploymentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatchServer_HandleDeploymentStatus_Call) RunAndReturn(run func(ctx context.Context, status *pb.DeploymentStatus) error) *MockDispatchServer_HandleDeploymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ReportStatus provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) ReportStatus(context1 context.Context, deploymentStatus *pb.DeploymentStatus) (*pb.ReportStatusOpts, error) {
	ret := _mock.Called(context1, deploymentStatus)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 *pb.ReportStatusOpts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeploymentStatus) (*pb.ReportStatusOpts, error)); ok {
		return returnFunc(context1, deploymentStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeploymentStatus) *pb.ReportStatusOpts); ok {
		r0 = returnFunc(context1, deploymentStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ReportStatusOpts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.DeploymentStatus) error); ok {
		r1 = returnFunc(context1, deploymentStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDispatchServer_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockDispatchServer_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - deploymentStatus *pb.DeploymentStatus
func (_e *MockDispatchServer_Expecter) ReportStatus(context1 any, deploymentStatus any) *MockDispatchServer_ReportStatus_Call {
	return &MockDispatchServer_ReportStatus_Call{Call: _e.mock.On("ReportStatus", context1, deploymentStatus)}
}

func (_c *MockDispatchServer_ReportStatus_Call) Run(run func(context1 context.Context, deploymentStatus *pb.DeploymentStatus)) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(*pb.DeploymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_ReportStatus_Call) Return(reportStatusOpts *pb.ReportStatusOpts, err error) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Return(reportStatusOpts, err)
	return _c
}

func (_c *MockDispatchServer_ReportStatus_Call) RunAndReturn(run func(context1 context.Context, deploymentStatus *pb.DeploymentStatus) (*pb.ReportStatusOpts, error)) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SendDeploymentRequest provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) SendDeploymentRequest(ctx context.Context, deployment *pb.DeploymentRequest) error {
	ret := _mock.Called(ctx, deployment)

	if len(ret) == 0 {
		panic("no return value specified for SendDeploymentRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeploymentRequest) error); ok {
		r0 = returnFunc(ctx, deployment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatchServer_SendDeploymentRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDeploymentRequest'
type MockDispatchServer_SendDeploymentRequest_Call struct {
	*mock.Call
}

// SendDeploymentRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - deployment *pb.DeploymentRequest
func (_e *MockDispatchServer_Expecter) SendDeploymentRequest(ctx any, deployment any) *MockDispatchServer_SendDeploymentRequest_Call {
	return &MockDispatchServer_SendDeploymentRequest_Call{Call: _e.mock.On("SendDeploymentRequest", ctx, deployment)}
}

func (_c *MockDispatchServer_SendDeploymentRequest_Call) Run(run func(ctx context.Context, deployment *pb.DeploymentRequest)) *MockDispatchServer_SendDeploymentRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pb.DeploymentRequest
		if args[1] != nil {
			arg1 = args[1].(*pb.DeploymentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_SendDeploymentRequest_Call) Return(err error) *MockDispatchServer_SendDeploymentRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatchServer_SendDeploymentRequest_Call) RunAndReturn(run func(ctx context.Context, deployment *pb.DeploymentRequest) error) *MockDispatchServer_SendDeploymentRequest_Call {
	_c.Call.Return(run)
	return _c
}

// StreamStatus provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) StreamStatus(context1 context.Context, deploymentStatusCh chan<- *pb.DeploymentStatus) {
	_mock.Called(context1, deploymentStatusCh)
	return
}

// MockDispatchServer_StreamStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamStatus'
type MockDispatchServer_StreamStatus_Call struct {
	*mock.Call
}

// StreamStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - deploymentStatusCh chan<- *pb.DeploymentStatus
func (_e *MockDispatchServer_Expecter) StreamStatus(context1 any, deploymentStatusCh any) *MockDispatchServer_StreamStatus_Call {
	return &MockDispatchServer_StreamStatus_Call{Call: _e.mock.On("StreamStatus", context1, deploymentStatusCh)}
}

func (_c *MockDispatchServer_StreamStatus_Call) Run(run func(context1 context.Context, deploymentStatusCh chan<- *pb.DeploymentStatus)) *MockDispatchServer_StreamStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- *pb.DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(chan<- *pb.DeploymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_StreamStatus_Call) Return() *MockDispatchServer_StreamStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatchServer_StreamStatus_Call) RunAndReturn(run func(context1 context.Context, deploymentStatusCh chan<- *pb.DeploymentStatus)) *MockDispatchServer_StreamStatus_Call {
	_c.Run(run)
	return _c
}

// mustEmbedUnimplementedDispatchServer provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) mustEmbedUnimplementedDispatchServer() {
	_mock.Called()
	return
}

// MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDispatchServer'
type MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDispatchServer is a helper method to define mock.On call
func (_e *MockDispatchServer_Expecter) mustEmbedUnimplementedDispatchServer() *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	return &MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDispatchServer")}
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Run(run func()) *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Return() *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) RunAndReturn(run func()) *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Run(run)
	return _c
}
