// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deployment/deployment.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GithubDeploymentState int32

const (
	GithubDeploymentState_success     GithubDeploymentState = 0
	GithubDeploymentState_error       GithubDeploymentState = 1
	GithubDeploymentState_failure     GithubDeploymentState = 2
	GithubDeploymentState_inactive    GithubDeploymentState = 3
	GithubDeploymentState_in_progress GithubDeploymentState = 4
	GithubDeploymentState_queued      GithubDeploymentState = 5
	GithubDeploymentState_pending     GithubDeploymentState = 6
)

var GithubDeploymentState_name = map[int32]string{
	0: "success",
	1: "error",
	2: "failure",
	3: "inactive",
	4: "in_progress",
	5: "queued",
	6: "pending",
}

var GithubDeploymentState_value = map[string]int32{
	"success":     0,
	"error":       1,
	"failure":     2,
	"inactive":    3,
	"in_progress": 4,
	"queued":      5,
	"pending":     6,
}

func (x GithubDeploymentState) String() string {
	return proto.EnumName(GithubDeploymentState_name, int32(x))
}

func (GithubDeploymentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{0}
}

type GithubRepository struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GithubRepository) Reset()         { *m = GithubRepository{} }
func (m *GithubRepository) String() string { return proto.CompactTextString(m) }
func (*GithubRepository) ProtoMessage()    {}
func (*GithubRepository) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{0}
}

func (m *GithubRepository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubRepository.Unmarshal(m, b)
}
func (m *GithubRepository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubRepository.Marshal(b, m, deterministic)
}
func (m *GithubRepository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubRepository.Merge(m, src)
}
func (m *GithubRepository) XXX_Size() int {
	return xxx_messageInfo_GithubRepository.Size(m)
}
func (m *GithubRepository) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubRepository.DiscardUnknown(m)
}

var xxx_messageInfo_GithubRepository proto.InternalMessageInfo

func (m *GithubRepository) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GithubRepository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeploymentSpec struct {
	Repository           *GithubRepository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	DeploymentID         int64             `protobuf:"varint,2,opt,name=deploymentID,proto3" json:"deploymentID,omitempty"`
	Environment          string            `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment,omitempty"`
	Ref                  string            `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeploymentSpec) Reset()         { *m = DeploymentSpec{} }
func (m *DeploymentSpec) String() string { return proto.CompactTextString(m) }
func (*DeploymentSpec) ProtoMessage()    {}
func (*DeploymentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{1}
}

func (m *DeploymentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentSpec.Unmarshal(m, b)
}
func (m *DeploymentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentSpec.Marshal(b, m, deterministic)
}
func (m *DeploymentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentSpec.Merge(m, src)
}
func (m *DeploymentSpec) XXX_Size() int {
	return xxx_messageInfo_DeploymentSpec.Size(m)
}
func (m *DeploymentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentSpec proto.InternalMessageInfo

func (m *DeploymentSpec) GetRepository() *GithubRepository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *DeploymentSpec) GetDeploymentID() int64 {
	if m != nil {
		return m.DeploymentID
	}
	return 0
}

func (m *DeploymentSpec) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *DeploymentSpec) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type Kubernetes struct {
	Resources            []*_struct.Struct `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Kubernetes) Reset()         { *m = Kubernetes{} }
func (m *Kubernetes) String() string { return proto.CompactTextString(m) }
func (*Kubernetes) ProtoMessage()    {}
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{2}
}

func (m *Kubernetes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kubernetes.Unmarshal(m, b)
}
func (m *Kubernetes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kubernetes.Marshal(b, m, deterministic)
}
func (m *Kubernetes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kubernetes.Merge(m, src)
}
func (m *Kubernetes) XXX_Size() int {
	return xxx_messageInfo_Kubernetes.Size(m)
}
func (m *Kubernetes) XXX_DiscardUnknown() {
	xxx_messageInfo_Kubernetes.DiscardUnknown(m)
}

var xxx_messageInfo_Kubernetes proto.InternalMessageInfo

func (m *Kubernetes) GetResources() []*_struct.Struct {
	if m != nil {
		return m.Resources
	}
	return nil
}

type Payload struct {
	Version              []int32     `protobuf:"varint,1,rep,packed,name=version,proto3" json:"version,omitempty"`
	Team                 string      `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Kubernetes           *Kubernetes `protobuf:"bytes,3,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{3}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() []int32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *Payload) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *Payload) GetKubernetes() *Kubernetes {
	if m != nil {
		return m.Kubernetes
	}
	return nil
}

type DeploymentRequest struct {
	Deployment           *DeploymentSpec      `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Deadline             int64                `protobuf:"varint,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Cluster              string               `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	DeliveryID           string               `protobuf:"bytes,6,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	PayloadSpec          *Payload             `protobuf:"bytes,7,opt,name=payloadSpec,proto3" json:"payloadSpec,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Status               *DeploymentStatus    `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeploymentRequest) Reset()         { *m = DeploymentRequest{} }
func (m *DeploymentRequest) String() string { return proto.CompactTextString(m) }
func (*DeploymentRequest) ProtoMessage()    {}
func (*DeploymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{4}
}

func (m *DeploymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentRequest.Unmarshal(m, b)
}
func (m *DeploymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentRequest.Marshal(b, m, deterministic)
}
func (m *DeploymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentRequest.Merge(m, src)
}
func (m *DeploymentRequest) XXX_Size() int {
	return xxx_messageInfo_DeploymentRequest.Size(m)
}
func (m *DeploymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentRequest proto.InternalMessageInfo

func (m *DeploymentRequest) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentRequest) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *DeploymentRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeploymentRequest) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

func (m *DeploymentRequest) GetPayloadSpec() *Payload {
	if m != nil {
		return m.PayloadSpec
	}
	return nil
}

func (m *DeploymentRequest) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *DeploymentRequest) GetStatus() *DeploymentStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeploymentStatus struct {
	Deployment           *DeploymentSpec       `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	State                GithubDeploymentState `protobuf:"varint,2,opt,name=state,proto3,enum=deployment.GithubDeploymentState" json:"state,omitempty"`
	Description          string                `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DeliveryID           string                `protobuf:"bytes,4,opt,name=deliveryID,proto3" json:"deliveryID,omitempty"`
	Team                 string                `protobuf:"bytes,5,opt,name=team,proto3" json:"team,omitempty"`
	Cluster              string                `protobuf:"bytes,6,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Time                 *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Id                   string                `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeploymentStatus) Reset()         { *m = DeploymentStatus{} }
func (m *DeploymentStatus) String() string { return proto.CompactTextString(m) }
func (*DeploymentStatus) ProtoMessage()    {}
func (*DeploymentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{5}
}

func (m *DeploymentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeploymentStatus.Unmarshal(m, b)
}
func (m *DeploymentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeploymentStatus.Marshal(b, m, deterministic)
}
func (m *DeploymentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeploymentStatus.Merge(m, src)
}
func (m *DeploymentStatus) XXX_Size() int {
	return xxx_messageInfo_DeploymentStatus.Size(m)
}
func (m *DeploymentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DeploymentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DeploymentStatus proto.InternalMessageInfo

func (m *DeploymentStatus) GetDeployment() *DeploymentSpec {
	if m != nil {
		return m.Deployment
	}
	return nil
}

func (m *DeploymentStatus) GetState() GithubDeploymentState {
	if m != nil {
		return m.State
	}
	return GithubDeploymentState_success
}

func (m *DeploymentStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeploymentStatus) GetDeliveryID() string {
	if m != nil {
		return m.DeliveryID
	}
	return ""
}

func (m *DeploymentStatus) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *DeploymentStatus) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *DeploymentStatus) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *DeploymentStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SignedMessage struct {
	Message              []byte   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedMessage) Reset()         { *m = SignedMessage{} }
func (m *SignedMessage) String() string { return proto.CompactTextString(m) }
func (*SignedMessage) ProtoMessage()    {}
func (*SignedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{6}
}

func (m *SignedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedMessage.Unmarshal(m, b)
}
func (m *SignedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedMessage.Marshal(b, m, deterministic)
}
func (m *SignedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedMessage.Merge(m, src)
}
func (m *SignedMessage) XXX_Size() int {
	return xxx_messageInfo_SignedMessage.Size(m)
}
func (m *SignedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SignedMessage proto.InternalMessageInfo

func (m *SignedMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SignedMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GetDeploymentOpts struct {
	Cluster              string   `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeploymentOpts) Reset()         { *m = GetDeploymentOpts{} }
func (m *GetDeploymentOpts) String() string { return proto.CompactTextString(m) }
func (*GetDeploymentOpts) ProtoMessage()    {}
func (*GetDeploymentOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{7}
}

func (m *GetDeploymentOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeploymentOpts.Unmarshal(m, b)
}
func (m *GetDeploymentOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeploymentOpts.Marshal(b, m, deterministic)
}
func (m *GetDeploymentOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeploymentOpts.Merge(m, src)
}
func (m *GetDeploymentOpts) XXX_Size() int {
	return xxx_messageInfo_GetDeploymentOpts.Size(m)
}
func (m *GetDeploymentOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeploymentOpts.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeploymentOpts proto.InternalMessageInfo

func (m *GetDeploymentOpts) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type ReportStatusOpts struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportStatusOpts) Reset()         { *m = ReportStatusOpts{} }
func (m *ReportStatusOpts) String() string { return proto.CompactTextString(m) }
func (*ReportStatusOpts) ProtoMessage()    {}
func (*ReportStatusOpts) Descriptor() ([]byte, []int) {
	return fileDescriptor_700de9d3ee114f41, []int{8}
}

func (m *ReportStatusOpts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportStatusOpts.Unmarshal(m, b)
}
func (m *ReportStatusOpts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportStatusOpts.Marshal(b, m, deterministic)
}
func (m *ReportStatusOpts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportStatusOpts.Merge(m, src)
}
func (m *ReportStatusOpts) XXX_Size() int {
	return xxx_messageInfo_ReportStatusOpts.Size(m)
}
func (m *ReportStatusOpts) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportStatusOpts.DiscardUnknown(m)
}

var xxx_messageInfo_ReportStatusOpts proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("deployment.GithubDeploymentState", GithubDeploymentState_name, GithubDeploymentState_value)
	proto.RegisterType((*GithubRepository)(nil), "deployment.GithubRepository")
	proto.RegisterType((*DeploymentSpec)(nil), "deployment.DeploymentSpec")
	proto.RegisterType((*Kubernetes)(nil), "deployment.Kubernetes")
	proto.RegisterType((*Payload)(nil), "deployment.Payload")
	proto.RegisterType((*DeploymentRequest)(nil), "deployment.DeploymentRequest")
	proto.RegisterType((*DeploymentStatus)(nil), "deployment.DeploymentStatus")
	proto.RegisterType((*SignedMessage)(nil), "deployment.SignedMessage")
	proto.RegisterType((*GetDeploymentOpts)(nil), "deployment.GetDeploymentOpts")
	proto.RegisterType((*ReportStatusOpts)(nil), "deployment.ReportStatusOpts")
}

func init() {
	proto.RegisterFile("deployment/deployment.proto", fileDescriptor_700de9d3ee114f41)
}

var fileDescriptor_700de9d3ee114f41 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x8d, 0x6c, 0xc9, 0x97, 0x91, 0x37, 0xab, 0x70, 0x6f, 0x82, 0x37, 0xd9, 0xcd, 0xea, 0x29,
	0x58, 0xa0, 0x4e, 0xe1, 0x36, 0x2d, 0x50, 0xe4, 0xa9, 0x0d, 0x10, 0x24, 0x6d, 0x91, 0x82, 0xe9,
	0x7b, 0x21, 0x4b, 0x13, 0x97, 0xa8, 0x4d, 0x2a, 0x24, 0xe5, 0xc2, 0x3f, 0xd4, 0xfe, 0x4a, 0xbf,
	0xa3, 0x5f, 0x52, 0x90, 0x92, 0x2d, 0xda, 0x09, 0x0a, 0x14, 0x7d, 0x9b, 0x39, 0x3c, 0xe4, 0xcc,
	0x9c, 0x39, 0x12, 0xfc, 0x9d, 0x63, 0x31, 0x13, 0xcb, 0x39, 0x72, 0x7d, 0xdc, 0x84, 0xa3, 0x42,
	0x0a, 0x2d, 0x08, 0x34, 0xc8, 0xf0, 0xdf, 0xa9, 0x10, 0xd3, 0x19, 0x1e, 0xdb, 0x93, 0x49, 0x79,
	0x73, 0xac, 0xd9, 0x1c, 0x95, 0x4e, 0xe7, 0x45, 0x45, 0x1e, 0xee, 0x6f, 0x13, 0x94, 0x96, 0x65,
	0x56, 0x3f, 0x95, 0x9c, 0x42, 0x74, 0xce, 0xf4, 0xfb, 0x72, 0x42, 0xb1, 0x10, 0x8a, 0x69, 0x21,
	0x97, 0xe4, 0x77, 0x08, 0xc4, 0x47, 0x8e, 0x32, 0xf6, 0x0e, 0xbd, 0xa3, 0x3e, 0xad, 0x12, 0x42,
	0xc0, 0xe7, 0xe9, 0x1c, 0xe3, 0x96, 0x05, 0x6d, 0x9c, 0x7c, 0xf2, 0x60, 0xf7, 0x6c, 0xdd, 0xcb,
	0x75, 0x81, 0x19, 0x39, 0x05, 0x90, 0xeb, 0xa7, 0xec, 0x0b, 0xe1, 0x78, 0x7f, 0xe4, 0x8c, 0xb0,
	0x5d, 0x8e, 0x3a, 0x7c, 0x92, 0xc0, 0xa0, 0xa1, 0x5e, 0x9c, 0xd9, 0x62, 0x6d, 0xba, 0x81, 0x91,
	0x43, 0x08, 0x91, 0x2f, 0x98, 0x14, 0xdc, 0x00, 0x71, 0xdb, 0xf6, 0xe3, 0x42, 0x24, 0x82, 0xb6,
	0xc4, 0x9b, 0xd8, 0xb7, 0x27, 0x26, 0x4c, 0x5e, 0x00, 0xbc, 0x2c, 0x27, 0x28, 0x39, 0x6a, 0x54,
	0xe4, 0x04, 0xfa, 0x12, 0x95, 0x28, 0x65, 0x86, 0x2a, 0xf6, 0x0e, 0xdb, 0x47, 0xe1, 0xf8, 0xaf,
	0x51, 0x25, 0xd3, 0x68, 0x25, 0xd3, 0xe8, 0xda, 0xca, 0x44, 0x1b, 0x66, 0x22, 0xa0, 0xfb, 0x26,
	0x5d, 0xce, 0x44, 0x9a, 0x93, 0x18, 0xba, 0x0b, 0x94, 0x8a, 0x09, 0x6e, 0xef, 0x07, 0x74, 0x95,
	0x1a, 0x99, 0x34, 0xa6, 0xf3, 0x95, 0x4c, 0x26, 0x26, 0x4f, 0x00, 0x3e, 0xac, 0xab, 0xdb, 0x86,
	0xc3, 0xf1, 0x9f, 0xae, 0x26, 0x4d, 0x6f, 0xd4, 0x61, 0x26, 0x5f, 0x5b, 0xb0, 0xd7, 0xc8, 0x4b,
	0xf1, 0xb6, 0x44, 0xa5, 0xc9, 0x33, 0x70, 0xf6, 0x5f, 0x2b, 0x3c, 0x74, 0x5f, 0xdb, 0xdc, 0x08,
	0x75, 0xd8, 0x64, 0x08, 0xbd, 0x1c, 0xd3, 0x7c, 0xc6, 0x38, 0xda, 0x3e, 0xda, 0x74, 0x9d, 0x9b,
	0x99, 0xb2, 0x59, 0xa9, 0x34, 0xca, 0x38, 0xb0, 0xcd, 0xaf, 0x52, 0xf2, 0x8f, 0xa9, 0x38, 0x63,
	0x0b, 0x94, 0xcb, 0x8b, 0xb3, 0xb8, 0x63, 0x0f, 0x1d, 0x84, 0x9c, 0x40, 0x58, 0x54, 0xc2, 0x98,
	0x82, 0x71, 0xd7, 0xb6, 0xf4, 0x9b, 0xdb, 0x52, 0xad, 0x1b, 0x75, 0x79, 0x64, 0x04, 0xbe, 0x31,
	0x6b, 0xdc, 0xab, 0x47, 0xd8, 0xde, 0xc0, 0xdb, 0x95, 0x93, 0xa9, 0xe5, 0x91, 0xc7, 0xd0, 0x51,
	0x3a, 0xd5, 0xa5, 0x8a, 0xfb, 0x77, 0x6d, 0xe5, 0x0c, 0x6d, 0x39, 0xb4, 0xe6, 0x5e, 0xfa, 0xbd,
	0x56, 0xd4, 0xbe, 0xf4, 0x7b, 0x7e, 0x14, 0xd0, 0xfe, 0xfa, 0xe3, 0xa0, 0xdd, 0xba, 0x93, 0xe4,
	0x4b, 0x0b, 0xa2, 0xed, 0xcb, 0x3f, 0xa5, 0xf1, 0x53, 0x08, 0x4c, 0xe9, 0xea, 0x4b, 0xd9, 0x1d,
	0xff, 0x77, 0xd7, 0xfc, 0x9b, 0xe5, 0x90, 0x56, 0x7c, 0x63, 0xec, 0x1c, 0x55, 0x26, 0x59, 0xa1,
	0x8d, 0xb1, 0x6a, 0x63, 0x3b, 0xd0, 0xd6, 0x22, 0xfc, 0x3b, 0x8b, 0x58, 0x99, 0x2f, 0x70, 0xcc,
	0xe7, 0xac, 0xb5, 0xb3, 0xb9, 0xd6, 0x1f, 0xd5, 0x7f, 0x17, 0x5a, 0x2c, 0xb7, 0xda, 0xf7, 0x69,
	0x8b, 0xe5, 0x97, 0x7e, 0xaf, 0x1b, 0xf5, 0x1c, 0x4d, 0x93, 0x73, 0xf8, 0xe5, 0x9a, 0x4d, 0x39,
	0xe6, 0xaf, 0x51, 0xa9, 0x74, 0x6a, 0x2d, 0x35, 0xaf, 0x42, 0xab, 0xe1, 0x80, 0xae, 0x52, 0xb2,
	0x0f, 0x7d, 0xc5, 0xa6, 0x3c, 0xd5, 0xa5, 0xac, 0x84, 0x1a, 0xd0, 0x06, 0x48, 0x1e, 0xc0, 0xde,
	0x39, 0xea, 0x46, 0xa6, 0xab, 0x42, 0x2b, 0x77, 0x10, 0x6f, 0x63, 0x90, 0x84, 0x40, 0x64, 0xfe,
	0x27, 0xb2, 0xde, 0x9e, 0x61, 0xff, 0xaf, 0xe1, 0x8f, 0x7b, 0xc5, 0x26, 0x21, 0x74, 0x55, 0x99,
	0x65, 0xa8, 0x54, 0xb4, 0x43, 0xfa, 0x10, 0xa0, 0x94, 0x42, 0x46, 0x9e, 0xc1, 0x6f, 0x52, 0x36,
	0x2b, 0x25, 0x46, 0x2d, 0x32, 0x80, 0x1e, 0xe3, 0x69, 0xa6, 0xd9, 0x02, 0xa3, 0x36, 0xf9, 0x15,
	0x42, 0xc6, 0xdf, 0x15, 0x52, 0x4c, 0xa5, 0xb9, 0xe6, 0x13, 0x80, 0xce, 0x6d, 0x89, 0x25, 0xe6,
	0x51, 0x60, 0xee, 0x15, 0xc8, 0x73, 0xc6, 0xa7, 0x51, 0x67, 0xfc, 0xd9, 0x83, 0x4e, 0x55, 0x90,
	0x5c, 0x41, 0xd8, 0x94, 0x56, 0xe4, 0x60, 0xc3, 0x06, 0xdb, 0xc3, 0x0d, 0x0f, 0xee, 0x37, 0x57,
	0xfd, 0xcd, 0x27, 0x3b, 0x0f, 0x3d, 0xf2, 0x0a, 0x06, 0xee, 0x94, 0xe4, 0xbb, 0xf6, 0x1f, 0x6e,
	0x9c, 0x6e, 0xab, 0x93, 0xec, 0x3c, 0x1f, 0x42, 0xcc, 0xc5, 0x88, 0xa7, 0x8b, 0x6a, 0xdf, 0xca,
	0xa1, 0x4f, 0x3a, 0x16, 0x7a, 0xf4, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x32, 0x3f, 0x38, 0x39, 0x85,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeployClient is the client API for Deploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeployClient interface {
	Deployments(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (Deploy_DeploymentsClient, error)
	ReportStatus(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error)
}

type deployClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployClient(cc grpc.ClientConnInterface) DeployClient {
	return &deployClient{cc}
}

func (c *deployClient) Deployments(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (Deploy_DeploymentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Deploy_serviceDesc.Streams[0], "/deployment.Deploy/Deployments", opts...)
	if err != nil {
		return nil, err
	}
	x := &deployDeploymentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Deploy_DeploymentsClient interface {
	Recv() (*DeploymentRequest, error)
	grpc.ClientStream
}

type deployDeploymentsClient struct {
	grpc.ClientStream
}

func (x *deployDeploymentsClient) Recv() (*DeploymentRequest, error) {
	m := new(DeploymentRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *deployClient) ReportStatus(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error) {
	out := new(ReportStatusOpts)
	err := c.cc.Invoke(ctx, "/deployment.Deploy/ReportStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployServer is the server API for Deploy service.
type DeployServer interface {
	Deployments(*GetDeploymentOpts, Deploy_DeploymentsServer) error
	ReportStatus(context.Context, *DeploymentStatus) (*ReportStatusOpts, error)
}

// UnimplementedDeployServer can be embedded to have forward compatible implementations.
type UnimplementedDeployServer struct {
}

func (*UnimplementedDeployServer) Deployments(req *GetDeploymentOpts, srv Deploy_DeploymentsServer) error {
	return status.Errorf(codes.Unimplemented, "method Deployments not implemented")
}
func (*UnimplementedDeployServer) ReportStatus(ctx context.Context, req *DeploymentStatus) (*ReportStatusOpts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}

func RegisterDeployServer(s *grpc.Server, srv DeployServer) {
	s.RegisterService(&_Deploy_serviceDesc, srv)
}

func _Deploy_Deployments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDeploymentOpts)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServer).Deployments(m, &deployDeploymentsServer{stream})
}

type Deploy_DeploymentsServer interface {
	Send(*DeploymentRequest) error
	grpc.ServerStream
}

type deployDeploymentsServer struct {
	grpc.ServerStream
}

func (x *deployDeploymentsServer) Send(m *DeploymentRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Deploy_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/deployment.Deploy/ReportStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).ReportStatus(ctx, req.(*DeploymentStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _Deploy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "deployment.Deploy",
	HandlerType: (*DeployServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _Deploy_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deployments",
			Handler:       _Deploy_Deployments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "deployment/deployment.proto",
}
