// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: pkg/pb/deployment.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dispatch_Deployments_FullMethodName  = "/pb.Dispatch/Deployments"
	Dispatch_ReportStatus_FullMethodName = "/pb.Dispatch/ReportStatus"
)

// DispatchClient is the client API for Dispatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is used by deployd.
type DispatchClient interface {
	// Continuous streaming of deployments that should be processed by deployd.
	Deployments(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentRequest], error)
	// Deployd returns back statuses for deploys using this API.
	ReportStatus(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error)
}

type dispatchClient struct {
	cc grpc.ClientConnInterface
}

func NewDispatchClient(cc grpc.ClientConnInterface) DispatchClient {
	return &dispatchClient{cc}
}

func (c *dispatchClient) Deployments(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Dispatch_ServiceDesc.Streams[0], Dispatch_Deployments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDeploymentOpts, DeploymentRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_DeploymentsClient = grpc.ServerStreamingClient[DeploymentRequest]

func (c *dispatchClient) ReportStatus(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusOpts)
	err := c.cc.Invoke(ctx, Dispatch_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DispatchServer is the server API for Dispatch service.
// All implementations must embed UnimplementedDispatchServer
// for forward compatibility.
//
// This service is used by deployd.
type DispatchServer interface {
	// Continuous streaming of deployments that should be processed by deployd.
	Deployments(*GetDeploymentOpts, grpc.ServerStreamingServer[DeploymentRequest]) error
	// Deployd returns back statuses for deploys using this API.
	ReportStatus(context.Context, *DeploymentStatus) (*ReportStatusOpts, error)
	mustEmbedUnimplementedDispatchServer()
}

// UnimplementedDispatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDispatchServer struct{}

func (UnimplementedDispatchServer) Deployments(*GetDeploymentOpts, grpc.ServerStreamingServer[DeploymentRequest]) error {
	return status.Errorf(codes.Unimplemented, "method Deployments not implemented")
}
func (UnimplementedDispatchServer) ReportStatus(context.Context, *DeploymentStatus) (*ReportStatusOpts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedDispatchServer) mustEmbedUnimplementedDispatchServer() {}
func (UnimplementedDispatchServer) testEmbeddedByValue()                  {}

// UnsafeDispatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DispatchServer will
// result in compilation errors.
type UnsafeDispatchServer interface {
	mustEmbedUnimplementedDispatchServer()
}

func RegisterDispatchServer(s grpc.ServiceRegistrar, srv DispatchServer) {
	// If the following call pancis, it indicates UnimplementedDispatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dispatch_ServiceDesc, srv)
}

func _Dispatch_Deployments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDeploymentOpts)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DispatchServer).Deployments(m, &grpc.GenericServerStream[GetDeploymentOpts, DeploymentRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Dispatch_DeploymentsServer = grpc.ServerStreamingServer[DeploymentRequest]

func _Dispatch_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatchServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dispatch_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatchServer).ReportStatus(ctx, req.(*DeploymentStatus))
	}
	return interceptor(ctx, in, info, handler)
}

// Dispatch_ServiceDesc is the grpc.ServiceDesc for Dispatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dispatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dispatch",
	HandlerType: (*DispatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _Dispatch_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deployments",
			Handler:       _Dispatch_Deployments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/pb/deployment.proto",
}

const (
	Deploy_Deploy_FullMethodName = "/pb.Deploy/Deploy"
	Deploy_Status_FullMethodName = "/pb.Deploy/Status"
)

// DeployClient is the client API for Deploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// This service is used by end-users in their CI pipelines.
type DeployClient interface {
	Deploy(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (*DeploymentStatus, error)
	Status(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentStatus], error)
}

type deployClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployClient(cc grpc.ClientConnInterface) DeployClient {
	return &deployClient{cc}
}

func (c *deployClient) Deploy(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (*DeploymentStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploymentStatus)
	err := c.cc.Invoke(ctx, Deploy_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployClient) Status(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Deploy_ServiceDesc.Streams[0], Deploy_Status_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeploymentRequest, DeploymentStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deploy_StatusClient = grpc.ServerStreamingClient[DeploymentStatus]

// DeployServer is the server API for Deploy service.
// All implementations must embed UnimplementedDeployServer
// for forward compatibility.
//
// This service is used by end-users in their CI pipelines.
type DeployServer interface {
	Deploy(context.Context, *DeploymentRequest) (*DeploymentStatus, error)
	Status(*DeploymentRequest, grpc.ServerStreamingServer[DeploymentStatus]) error
	mustEmbedUnimplementedDeployServer()
}

// UnimplementedDeployServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployServer struct{}

func (UnimplementedDeployServer) Deploy(context.Context, *DeploymentRequest) (*DeploymentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedDeployServer) Status(*DeploymentRequest, grpc.ServerStreamingServer[DeploymentStatus]) error {
	return status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedDeployServer) mustEmbedUnimplementedDeployServer() {}
func (UnimplementedDeployServer) testEmbeddedByValue()                {}

// UnsafeDeployServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployServer will
// result in compilation errors.
type UnsafeDeployServer interface {
	mustEmbedUnimplementedDeployServer()
}

func RegisterDeployServer(s grpc.ServiceRegistrar, srv DeployServer) {
	// If the following call pancis, it indicates UnimplementedDeployServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Deploy_ServiceDesc, srv)
}

func _Deploy_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Deploy_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployServer).Deploy(ctx, req.(*DeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Deploy_Status_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DeploymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployServer).Status(m, &grpc.GenericServerStream[DeploymentRequest, DeploymentStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Deploy_StatusServer = grpc.ServerStreamingServer[DeploymentStatus]

// Deploy_ServiceDesc is the grpc.ServiceDesc for Deploy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Deploy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Deploy",
	HandlerType: (*DeployServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _Deploy_Deploy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Status",
			Handler:       _Deploy_Status_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/pb/deployment.proto",
}
