// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockDeploy_StatusServer creates a new instance of MockDeploy_StatusServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploy_StatusServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploy_StatusServer {
	mock := &MockDeploy_StatusServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploy_StatusServer is an autogenerated mock type for the Deploy_StatusServer type
type MockDeploy_StatusServer struct {
	mock.Mock
}

type MockDeploy_StatusServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploy_StatusServer) EXPECT() *MockDeploy_StatusServer_Expecter {
	return &MockDeploy_StatusServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockDeploy_StatusServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockDeploy_StatusServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockDeploy_StatusServer_Expecter) Context() *MockDeploy_StatusServer_Context_Call {
	return &MockDeploy_StatusServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockDeploy_StatusServer_Context_Call) Run(run func()) *MockDeploy_StatusServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusServer_Context_Call) Return(context1 context.Context) *MockDeploy_StatusServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockDeploy_StatusServer_Context_Call) RunAndReturn(run func() context.Context) *MockDeploy_StatusServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockDeploy_StatusServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDeploy_StatusServer_Expecter) RecvMsg(m any) *MockDeploy_StatusServer_RecvMsg_Call {
	return &MockDeploy_StatusServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockDeploy_StatusServer_RecvMsg_Call) Run(run func(m any)) *MockDeploy_StatusServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_RecvMsg_Call) Return(err error) *MockDeploy_StatusServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockDeploy_StatusServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) Send(deploymentStatus *DeploymentStatus) error {
	ret := _mock.Called(deploymentStatus)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*DeploymentStatus) error); ok {
		r0 = returnFunc(deploymentStatus)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDeploy_StatusServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - deploymentStatus *DeploymentStatus
func (_e *MockDeploy_StatusServer_Expecter) Send(deploymentStatus any) *MockDeploy_StatusServer_Send_Call {
	return &MockDeploy_StatusServer_Send_Call{Call: _e.mock.On("Send", deploymentStatus)}
}

func (_c *MockDeploy_StatusServer_Send_Call) Run(run func(deploymentStatus *DeploymentStatus)) *MockDeploy_StatusServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *DeploymentStatus
		if args[0] != nil {
			arg0 = args[0].(*DeploymentStatus)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_Send_Call) Return(err error) *MockDeploy_StatusServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusServer_Send_Call) RunAndReturn(run func(deploymentStatus *DeploymentStatus) error) *MockDeploy_StatusServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockDeploy_StatusServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDeploy_StatusServer_Expecter) SendHeader(mD any) *MockDeploy_StatusServer_SendHeader_Call {
	return &MockDeploy_StatusServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockDeploy_StatusServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockDeploy_StatusServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_SendHeader_Call) Return(err error) *MockDeploy_StatusServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockDeploy_StatusServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockDeploy_StatusServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDeploy_StatusServer_Expecter) SendMsg(m any) *MockDeploy_StatusServer_SendMsg_Call {
	return &MockDeploy_StatusServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockDeploy_StatusServer_SendMsg_Call) Run(run func(m any)) *MockDeploy_StatusServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_SendMsg_Call) Return(err error) *MockDeploy_StatusServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockDeploy_StatusServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockDeploy_StatusServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDeploy_StatusServer_Expecter) SetHeader(mD any) *MockDeploy_StatusServer_SetHeader_Call {
	return &MockDeploy_StatusServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockDeploy_StatusServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockDeploy_StatusServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_SetHeader_Call) Return(err error) *MockDeploy_StatusServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockDeploy_StatusServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockDeploy_StatusServer
func (_mock *MockDeploy_StatusServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockDeploy_StatusServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockDeploy_StatusServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDeploy_StatusServer_Expecter) SetTrailer(mD any) *MockDeploy_StatusServer_SetTrailer_Call {
	return &MockDeploy_StatusServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockDeploy_StatusServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockDeploy_StatusServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusServer_SetTrailer_Call) Return() *MockDeploy_StatusServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeploy_StatusServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockDeploy_StatusServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
