// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockDispatchClient creates a new instance of MockDispatchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatchClient {
	mock := &MockDispatchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatchClient is an autogenerated mock type for the DispatchClient type
type MockDispatchClient struct {
	mock.Mock
}

type MockDispatchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatchClient) EXPECT() *MockDispatchClient_Expecter {
	return &MockDispatchClient_Expecter{mock: &_m.Mock}
}

// Deployments provides a mock function for the type MockDispatchClient
func (_mock *MockDispatchClient) Deployments(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentRequest], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 grpc.ServerStreamingClient[DeploymentRequest]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetDeploymentOpts, ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentRequest], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *GetDeploymentOpts, ...grpc.CallOption) grpc.ServerStreamingClient[DeploymentRequest]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[DeploymentRequest])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *GetDeploymentOpts, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDispatchClient_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type MockDispatchClient_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetDeploymentOpts
//   - opts ...grpc.CallOption
func (_e *MockDispatchClient_Expecter) Deployments(ctx any, in any, opts ...any) *MockDispatchClient_Deployments_Call {
	return &MockDispatchClient_Deployments_Call{Call: _e.mock.On("Deployments",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockDispatchClient_Deployments_Call) Run(run func(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption)) *MockDispatchClient_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *GetDeploymentOpts
		if args[1] != nil {
			arg1 = args[1].(*GetDeploymentOpts)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDispatchClient_Deployments_Call) Return(serverStreamingClient grpc.ServerStreamingClient[DeploymentRequest], err error) *MockDispatchClient_Deployments_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockDispatchClient_Deployments_Call) RunAndReturn(run func(ctx context.Context, in *GetDeploymentOpts, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentRequest], error)) *MockDispatchClient_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// ReportStatus provides a mock function for the type MockDispatchClient
func (_mock *MockDispatchClient) ReportStatus(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 *ReportStatusOpts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentStatus, ...grpc.CallOption) (*ReportStatusOpts, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentStatus, ...grpc.CallOption) *ReportStatusOpts); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReportStatusOpts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeploymentStatus, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDispatchClient_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockDispatchClient_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DeploymentStatus
//   - opts ...grpc.CallOption
func (_e *MockDispatchClient_Expecter) ReportStatus(ctx any, in any, opts ...any) *MockDispatchClient_ReportStatus_Call {
	return &MockDispatchClient_ReportStatus_Call{Call: _e.mock.On("ReportStatus",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockDispatchClient_ReportStatus_Call) Run(run func(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption)) *MockDispatchClient_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(*DeploymentStatus)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDispatchClient_ReportStatus_Call) Return(reportStatusOpts *ReportStatusOpts, err error) *MockDispatchClient_ReportStatus_Call {
	_c.Call.Return(reportStatusOpts, err)
	return _c
}

func (_c *MockDispatchClient_ReportStatus_Call) RunAndReturn(run func(ctx context.Context, in *DeploymentStatus, opts ...grpc.CallOption) (*ReportStatusOpts, error)) *MockDispatchClient_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}
