// Code generated by mockery vv2.7.1. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDeployServer is an autogenerated mock type for the UnsafeDeployServer type
type MockUnsafeDeployServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDeployServer provides a mock function with given fields:
func (_m *MockUnsafeDeployServer) mustEmbedUnimplementedDeployServer() {
	_m.Called()
}
