// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockDeployServer creates a new instance of MockDeployServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeployServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeployServer {
	mock := &MockDeployServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeployServer is an autogenerated mock type for the DeployServer type
type MockDeployServer struct {
	mock.Mock
}

type MockDeployServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeployServer) EXPECT() *MockDeployServer_Expecter {
	return &MockDeployServer_Expecter{mock: &_m.Mock}
}

// Deploy provides a mock function for the type MockDeployServer
func (_mock *MockDeployServer) Deploy(context1 context.Context, deploymentRequest *DeploymentRequest) (*DeploymentStatus, error) {
	ret := _mock.Called(context1, deploymentRequest)

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 *DeploymentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest) (*DeploymentStatus, error)); ok {
		return returnFunc(context1, deploymentRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest) *DeploymentStatus); ok {
		r0 = returnFunc(context1, deploymentRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeploymentStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeploymentRequest) error); ok {
		r1 = returnFunc(context1, deploymentRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeployServer_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockDeployServer_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - context1 context.Context
//   - deploymentRequest *DeploymentRequest
func (_e *MockDeployServer_Expecter) Deploy(context1 any, deploymentRequest any) *MockDeployServer_Deploy_Call {
	return &MockDeployServer_Deploy_Call{Call: _e.mock.On("Deploy", context1, deploymentRequest)}
}

func (_c *MockDeployServer_Deploy_Call) Run(run func(context1 context.Context, deploymentRequest *DeploymentRequest)) *MockDeployServer_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeploymentRequest
		if args[1] != nil {
			arg1 = args[1].(*DeploymentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeployServer_Deploy_Call) Return(deploymentStatus *DeploymentStatus, err error) *MockDeployServer_Deploy_Call {
	_c.Call.Return(deploymentStatus, err)
	return _c
}

func (_c *MockDeployServer_Deploy_Call) RunAndReturn(run func(context1 context.Context, deploymentRequest *DeploymentRequest) (*DeploymentStatus, error)) *MockDeployServer_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockDeployServer
func (_mock *MockDeployServer) Status(deploymentRequest *DeploymentRequest, serverStreamingServer grpc.ServerStreamingServer[DeploymentStatus]) error {
	ret := _mock.Called(deploymentRequest, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*DeploymentRequest, grpc.ServerStreamingServer[DeploymentStatus]) error); ok {
		r0 = returnFunc(deploymentRequest, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeployServer_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockDeployServer_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - deploymentRequest *DeploymentRequest
//   - serverStreamingServer grpc.ServerStreamingServer[DeploymentStatus]
func (_e *MockDeployServer_Expecter) Status(deploymentRequest any, serverStreamingServer any) *MockDeployServer_Status_Call {
	return &MockDeployServer_Status_Call{Call: _e.mock.On("Status", deploymentRequest, serverStreamingServer)}
}

func (_c *MockDeployServer_Status_Call) Run(run func(deploymentRequest *DeploymentRequest, serverStreamingServer grpc.ServerStreamingServer[DeploymentStatus])) *MockDeployServer_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *DeploymentRequest
		if args[0] != nil {
			arg0 = args[0].(*DeploymentRequest)
		}
		var arg1 grpc.ServerStreamingServer[DeploymentStatus]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[DeploymentStatus])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeployServer_Status_Call) Return(err error) *MockDeployServer_Status_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeployServer_Status_Call) RunAndReturn(run func(deploymentRequest *DeploymentRequest, serverStreamingServer grpc.ServerStreamingServer[DeploymentStatus]) error) *MockDeployServer_Status_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedDeployServer provides a mock function for the type MockDeployServer
func (_mock *MockDeployServer) mustEmbedUnimplementedDeployServer() {
	_mock.Called()
	return
}

// MockDeployServer_mustEmbedUnimplementedDeployServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDeployServer'
type MockDeployServer_mustEmbedUnimplementedDeployServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDeployServer is a helper method to define mock.On call
func (_e *MockDeployServer_Expecter) mustEmbedUnimplementedDeployServer() *MockDeployServer_mustEmbedUnimplementedDeployServer_Call {
	return &MockDeployServer_mustEmbedUnimplementedDeployServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDeployServer")}
}

func (_c *MockDeployServer_mustEmbedUnimplementedDeployServer_Call) Run(run func()) *MockDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeployServer_mustEmbedUnimplementedDeployServer_Call) Return() *MockDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeployServer_mustEmbedUnimplementedDeployServer_Call) RunAndReturn(run func()) *MockDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Run(run)
	return _c
}
