// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeDeployServer creates a new instance of MockUnsafeDeployServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeDeployServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeDeployServer {
	mock := &MockUnsafeDeployServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeDeployServer is an autogenerated mock type for the UnsafeDeployServer type
type MockUnsafeDeployServer struct {
	mock.Mock
}

type MockUnsafeDeployServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeDeployServer) EXPECT() *MockUnsafeDeployServer_Expecter {
	return &MockUnsafeDeployServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedDeployServer provides a mock function for the type MockUnsafeDeployServer
func (_mock *MockUnsafeDeployServer) mustEmbedUnimplementedDeployServer() {
	_mock.Called()
	return
}

// MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDeployServer'
type MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDeployServer is a helper method to define mock.On call
func (_e *MockUnsafeDeployServer_Expecter) mustEmbedUnimplementedDeployServer() *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call {
	return &MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDeployServer")}
}

func (_c *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call) Run(run func()) *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call) Return() *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call) RunAndReturn(run func()) *MockUnsafeDeployServer_mustEmbedUnimplementedDeployServer_Call {
	_c.Run(run)
	return _c
}
