// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockDispatch_DeploymentsServer creates a new instance of MockDispatch_DeploymentsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatch_DeploymentsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatch_DeploymentsServer {
	mock := &MockDispatch_DeploymentsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatch_DeploymentsServer is an autogenerated mock type for the Dispatch_DeploymentsServer type
type MockDispatch_DeploymentsServer struct {
	mock.Mock
}

type MockDispatch_DeploymentsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatch_DeploymentsServer) EXPECT() *MockDispatch_DeploymentsServer_Expecter {
	return &MockDispatch_DeploymentsServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockDispatch_DeploymentsServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockDispatch_DeploymentsServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockDispatch_DeploymentsServer_Expecter) Context() *MockDispatch_DeploymentsServer_Context_Call {
	return &MockDispatch_DeploymentsServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockDispatch_DeploymentsServer_Context_Call) Run(run func()) *MockDispatch_DeploymentsServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_Context_Call) Return(context1 context.Context) *MockDispatch_DeploymentsServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_Context_Call) RunAndReturn(run func() context.Context) *MockDispatch_DeploymentsServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatch_DeploymentsServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockDispatch_DeploymentsServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDispatch_DeploymentsServer_Expecter) RecvMsg(m any) *MockDispatch_DeploymentsServer_RecvMsg_Call {
	return &MockDispatch_DeploymentsServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockDispatch_DeploymentsServer_RecvMsg_Call) Run(run func(m any)) *MockDispatch_DeploymentsServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_RecvMsg_Call) Return(err error) *MockDispatch_DeploymentsServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockDispatch_DeploymentsServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) Send(deploymentRequest *DeploymentRequest) error {
	ret := _mock.Called(deploymentRequest)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*DeploymentRequest) error); ok {
		r0 = returnFunc(deploymentRequest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatch_DeploymentsServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDispatch_DeploymentsServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - deploymentRequest *DeploymentRequest
func (_e *MockDispatch_DeploymentsServer_Expecter) Send(deploymentRequest any) *MockDispatch_DeploymentsServer_Send_Call {
	return &MockDispatch_DeploymentsServer_Send_Call{Call: _e.mock.On("Send", deploymentRequest)}
}

func (_c *MockDispatch_DeploymentsServer_Send_Call) Run(run func(deploymentRequest *DeploymentRequest)) *MockDispatch_DeploymentsServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *DeploymentRequest
		if args[0] != nil {
			arg0 = args[0].(*DeploymentRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_Send_Call) Return(err error) *MockDispatch_DeploymentsServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_Send_Call) RunAndReturn(run func(deploymentRequest *DeploymentRequest) error) *MockDispatch_DeploymentsServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatch_DeploymentsServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockDispatch_DeploymentsServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDispatch_DeploymentsServer_Expecter) SendHeader(mD any) *MockDispatch_DeploymentsServer_SendHeader_Call {
	return &MockDispatch_DeploymentsServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockDispatch_DeploymentsServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockDispatch_DeploymentsServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SendHeader_Call) Return(err error) *MockDispatch_DeploymentsServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockDispatch_DeploymentsServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatch_DeploymentsServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockDispatch_DeploymentsServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDispatch_DeploymentsServer_Expecter) SendMsg(m any) *MockDispatch_DeploymentsServer_SendMsg_Call {
	return &MockDispatch_DeploymentsServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockDispatch_DeploymentsServer_SendMsg_Call) Run(run func(m any)) *MockDispatch_DeploymentsServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SendMsg_Call) Return(err error) *MockDispatch_DeploymentsServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockDispatch_DeploymentsServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatch_DeploymentsServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockDispatch_DeploymentsServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDispatch_DeploymentsServer_Expecter) SetHeader(mD any) *MockDispatch_DeploymentsServer_SetHeader_Call {
	return &MockDispatch_DeploymentsServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockDispatch_DeploymentsServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockDispatch_DeploymentsServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SetHeader_Call) Return(err error) *MockDispatch_DeploymentsServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockDispatch_DeploymentsServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockDispatch_DeploymentsServer
func (_mock *MockDispatch_DeploymentsServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockDispatch_DeploymentsServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockDispatch_DeploymentsServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockDispatch_DeploymentsServer_Expecter) SetTrailer(mD any) *MockDispatch_DeploymentsServer_SetTrailer_Call {
	return &MockDispatch_DeploymentsServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockDispatch_DeploymentsServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockDispatch_DeploymentsServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SetTrailer_Call) Return() *MockDispatch_DeploymentsServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatch_DeploymentsServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockDispatch_DeploymentsServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
