// Code generated by mockery v2.20.0. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDeployServer is an autogenerated mock type for the UnsafeDeployServer type
type MockUnsafeDeployServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDeployServer provides a mock function with given fields:
func (_m *MockUnsafeDeployServer) mustEmbedUnimplementedDeployServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeDeployServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeDeployServer creates a new instance of MockUnsafeDeployServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeDeployServer(t mockConstructorTestingTNewMockUnsafeDeployServer) *MockUnsafeDeployServer {
	mock := &MockUnsafeDeployServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
