// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockDeploy_StatusClient creates a new instance of MockDeploy_StatusClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeploy_StatusClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeploy_StatusClient {
	mock := &MockDeploy_StatusClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeploy_StatusClient is an autogenerated mock type for the Deploy_StatusClient type
type MockDeploy_StatusClient struct {
	mock.Mock
}

type MockDeploy_StatusClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeploy_StatusClient) EXPECT() *MockDeploy_StatusClient_Expecter {
	return &MockDeploy_StatusClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockDeploy_StatusClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockDeploy_StatusClient_Expecter) CloseSend() *MockDeploy_StatusClient_CloseSend_Call {
	return &MockDeploy_StatusClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockDeploy_StatusClient_CloseSend_Call) Run(run func()) *MockDeploy_StatusClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusClient_CloseSend_Call) Return(err error) *MockDeploy_StatusClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusClient_CloseSend_Call) RunAndReturn(run func() error) *MockDeploy_StatusClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockDeploy_StatusClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockDeploy_StatusClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockDeploy_StatusClient_Expecter) Context() *MockDeploy_StatusClient_Context_Call {
	return &MockDeploy_StatusClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockDeploy_StatusClient_Context_Call) Run(run func()) *MockDeploy_StatusClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusClient_Context_Call) Return(context1 context.Context) *MockDeploy_StatusClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockDeploy_StatusClient_Context_Call) RunAndReturn(run func() context.Context) *MockDeploy_StatusClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploy_StatusClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockDeploy_StatusClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockDeploy_StatusClient_Expecter) Header() *MockDeploy_StatusClient_Header_Call {
	return &MockDeploy_StatusClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockDeploy_StatusClient_Header_Call) Run(run func()) *MockDeploy_StatusClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusClient_Header_Call) Return(mD metadata.MD, err error) *MockDeploy_StatusClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockDeploy_StatusClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockDeploy_StatusClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) Recv() (*DeploymentStatus, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *DeploymentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*DeploymentStatus, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *DeploymentStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeploymentStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeploy_StatusClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockDeploy_StatusClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockDeploy_StatusClient_Expecter) Recv() *MockDeploy_StatusClient_Recv_Call {
	return &MockDeploy_StatusClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockDeploy_StatusClient_Recv_Call) Run(run func()) *MockDeploy_StatusClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusClient_Recv_Call) Return(deploymentStatus *DeploymentStatus, err error) *MockDeploy_StatusClient_Recv_Call {
	_c.Call.Return(deploymentStatus, err)
	return _c
}

func (_c *MockDeploy_StatusClient_Recv_Call) RunAndReturn(run func() (*DeploymentStatus, error)) *MockDeploy_StatusClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockDeploy_StatusClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDeploy_StatusClient_Expecter) RecvMsg(m any) *MockDeploy_StatusClient_RecvMsg_Call {
	return &MockDeploy_StatusClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockDeploy_StatusClient_RecvMsg_Call) Run(run func(m any)) *MockDeploy_StatusClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusClient_RecvMsg_Call) Return(err error) *MockDeploy_StatusClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockDeploy_StatusClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeploy_StatusClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockDeploy_StatusClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockDeploy_StatusClient_Expecter) SendMsg(m any) *MockDeploy_StatusClient_SendMsg_Call {
	return &MockDeploy_StatusClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockDeploy_StatusClient_SendMsg_Call) Run(run func(m any)) *MockDeploy_StatusClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeploy_StatusClient_SendMsg_Call) Return(err error) *MockDeploy_StatusClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeploy_StatusClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockDeploy_StatusClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockDeploy_StatusClient
func (_mock *MockDeploy_StatusClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockDeploy_StatusClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockDeploy_StatusClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockDeploy_StatusClient_Expecter) Trailer() *MockDeploy_StatusClient_Trailer_Call {
	return &MockDeploy_StatusClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockDeploy_StatusClient_Trailer_Call) Run(run func()) *MockDeploy_StatusClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeploy_StatusClient_Trailer_Call) Return(mD metadata.MD) *MockDeploy_StatusClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockDeploy_StatusClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockDeploy_StatusClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
