// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockDeployClient creates a new instance of MockDeployClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeployClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeployClient {
	mock := &MockDeployClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeployClient is an autogenerated mock type for the DeployClient type
type MockDeployClient struct {
	mock.Mock
}

type MockDeployClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeployClient) EXPECT() *MockDeployClient_Expecter {
	return &MockDeployClient_Expecter{mock: &_m.Mock}
}

// Deploy provides a mock function for the type MockDeployClient
func (_mock *MockDeployClient) Deploy(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (*DeploymentStatus, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deploy")
	}

	var r0 *DeploymentStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) (*DeploymentStatus, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) *DeploymentStatus); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeploymentStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeployClient_Deploy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deploy'
type MockDeployClient_Deploy_Call struct {
	*mock.Call
}

// Deploy is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DeploymentRequest
//   - opts ...grpc.CallOption
func (_e *MockDeployClient_Expecter) Deploy(ctx any, in any, opts ...any) *MockDeployClient_Deploy_Call {
	return &MockDeployClient_Deploy_Call{Call: _e.mock.On("Deploy",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockDeployClient_Deploy_Call) Run(run func(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption)) *MockDeployClient_Deploy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeploymentRequest
		if args[1] != nil {
			arg1 = args[1].(*DeploymentRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDeployClient_Deploy_Call) Return(deploymentStatus *DeploymentStatus, err error) *MockDeployClient_Deploy_Call {
	_c.Call.Return(deploymentStatus, err)
	return _c
}

func (_c *MockDeployClient_Deploy_Call) RunAndReturn(run func(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (*DeploymentStatus, error)) *MockDeployClient_Deploy_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockDeployClient
func (_mock *MockDeployClient) Status(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentStatus], error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 grpc.ServerStreamingClient[DeploymentStatus]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentStatus], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) grpc.ServerStreamingClient[DeploymentStatus]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[DeploymentStatus])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeploymentRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeployClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockDeployClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DeploymentRequest
//   - opts ...grpc.CallOption
func (_e *MockDeployClient_Expecter) Status(ctx any, in any, opts ...any) *MockDeployClient_Status_Call {
	return &MockDeployClient_Status_Call{Call: _e.mock.On("Status",
		append([]any{ctx, in}, opts...)...)}
}

func (_c *MockDeployClient_Status_Call) Run(run func(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption)) *MockDeployClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeploymentRequest
		if args[1] != nil {
			arg1 = args[1].(*DeploymentRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDeployClient_Status_Call) Return(serverStreamingClient grpc.ServerStreamingClient[DeploymentStatus], err error) *MockDeployClient_Status_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockDeployClient_Status_Call) RunAndReturn(run func(ctx context.Context, in *DeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeploymentStatus], error)) *MockDeployClient_Status_Call {
	_c.Call.Return(run)
	return _c
}
