// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeDispatchServer creates a new instance of MockUnsafeDispatchServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeDispatchServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeDispatchServer {
	mock := &MockUnsafeDispatchServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeDispatchServer is an autogenerated mock type for the UnsafeDispatchServer type
type MockUnsafeDispatchServer struct {
	mock.Mock
}

type MockUnsafeDispatchServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeDispatchServer) EXPECT() *MockUnsafeDispatchServer_Expecter {
	return &MockUnsafeDispatchServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedDispatchServer provides a mock function for the type MockUnsafeDispatchServer
func (_mock *MockUnsafeDispatchServer) mustEmbedUnimplementedDispatchServer() {
	_mock.Called()
	return
}

// MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDispatchServer'
type MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDispatchServer is a helper method to define mock.On call
func (_e *MockUnsafeDispatchServer_Expecter) mustEmbedUnimplementedDispatchServer() *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	return &MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDispatchServer")}
}

func (_c *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Run(run func()) *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Return() *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call) RunAndReturn(run func()) *MockUnsafeDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Run(run)
	return _c
}
