// Code generated by mockery vv2.7.1. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDispatchServer is an autogenerated mock type for the UnsafeDispatchServer type
type MockUnsafeDispatchServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDispatchServer provides a mock function with given fields:
func (_m *MockUnsafeDispatchServer) mustEmbedUnimplementedDispatchServer() {
	_m.Called()
}
