// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockDispatchServer creates a new instance of MockDispatchServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatchServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatchServer {
	mock := &MockDispatchServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDispatchServer is an autogenerated mock type for the DispatchServer type
type MockDispatchServer struct {
	mock.Mock
}

type MockDispatchServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDispatchServer) EXPECT() *MockDispatchServer_Expecter {
	return &MockDispatchServer_Expecter{mock: &_m.Mock}
}

// Deployments provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) Deployments(getDeploymentOpts *GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[DeploymentRequest]) error {
	ret := _mock.Called(getDeploymentOpts, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for Deployments")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*GetDeploymentOpts, grpc.ServerStreamingServer[DeploymentRequest]) error); ok {
		r0 = returnFunc(getDeploymentOpts, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDispatchServer_Deployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deployments'
type MockDispatchServer_Deployments_Call struct {
	*mock.Call
}

// Deployments is a helper method to define mock.On call
//   - getDeploymentOpts *GetDeploymentOpts
//   - serverStreamingServer grpc.ServerStreamingServer[DeploymentRequest]
func (_e *MockDispatchServer_Expecter) Deployments(getDeploymentOpts any, serverStreamingServer any) *MockDispatchServer_Deployments_Call {
	return &MockDispatchServer_Deployments_Call{Call: _e.mock.On("Deployments", getDeploymentOpts, serverStreamingServer)}
}

func (_c *MockDispatchServer_Deployments_Call) Run(run func(getDeploymentOpts *GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[DeploymentRequest])) *MockDispatchServer_Deployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *GetDeploymentOpts
		if args[0] != nil {
			arg0 = args[0].(*GetDeploymentOpts)
		}
		var arg1 grpc.ServerStreamingServer[DeploymentRequest]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[DeploymentRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_Deployments_Call) Return(err error) *MockDispatchServer_Deployments_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDispatchServer_Deployments_Call) RunAndReturn(run func(getDeploymentOpts *GetDeploymentOpts, serverStreamingServer grpc.ServerStreamingServer[DeploymentRequest]) error) *MockDispatchServer_Deployments_Call {
	_c.Call.Return(run)
	return _c
}

// ReportStatus provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) ReportStatus(context1 context.Context, deploymentStatus *DeploymentStatus) (*ReportStatusOpts, error) {
	ret := _mock.Called(context1, deploymentStatus)

	if len(ret) == 0 {
		panic("no return value specified for ReportStatus")
	}

	var r0 *ReportStatusOpts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentStatus) (*ReportStatusOpts, error)); ok {
		return returnFunc(context1, deploymentStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *DeploymentStatus) *ReportStatusOpts); ok {
		r0 = returnFunc(context1, deploymentStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReportStatusOpts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *DeploymentStatus) error); ok {
		r1 = returnFunc(context1, deploymentStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDispatchServer_ReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportStatus'
type MockDispatchServer_ReportStatus_Call struct {
	*mock.Call
}

// ReportStatus is a helper method to define mock.On call
//   - context1 context.Context
//   - deploymentStatus *DeploymentStatus
func (_e *MockDispatchServer_Expecter) ReportStatus(context1 any, deploymentStatus any) *MockDispatchServer_ReportStatus_Call {
	return &MockDispatchServer_ReportStatus_Call{Call: _e.mock.On("ReportStatus", context1, deploymentStatus)}
}

func (_c *MockDispatchServer_ReportStatus_Call) Run(run func(context1 context.Context, deploymentStatus *DeploymentStatus)) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *DeploymentStatus
		if args[1] != nil {
			arg1 = args[1].(*DeploymentStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDispatchServer_ReportStatus_Call) Return(reportStatusOpts *ReportStatusOpts, err error) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Return(reportStatusOpts, err)
	return _c
}

func (_c *MockDispatchServer_ReportStatus_Call) RunAndReturn(run func(context1 context.Context, deploymentStatus *DeploymentStatus) (*ReportStatusOpts, error)) *MockDispatchServer_ReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedDispatchServer provides a mock function for the type MockDispatchServer
func (_mock *MockDispatchServer) mustEmbedUnimplementedDispatchServer() {
	_mock.Called()
	return
}

// MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedDispatchServer'
type MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedDispatchServer is a helper method to define mock.On call
func (_e *MockDispatchServer_Expecter) mustEmbedUnimplementedDispatchServer() *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	return &MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call{Call: _e.mock.On("mustEmbedUnimplementedDispatchServer")}
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Run(run func()) *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) Return() *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call) RunAndReturn(run func()) *MockDispatchServer_mustEmbedUnimplementedDispatchServer_Call {
	_c.Run(run)
	return _c
}
