// Code generated by mockery v2.33.2. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeDispatchServer is an autogenerated mock type for the UnsafeDispatchServer type
type MockUnsafeDispatchServer struct {
	mock.Mock
}

// mustEmbedUnimplementedDispatchServer provides a mock function with given fields:
func (_m *MockUnsafeDispatchServer) mustEmbedUnimplementedDispatchServer() {
	_m.Called()
}

// NewMockUnsafeDispatchServer creates a new instance of MockUnsafeDispatchServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeDispatchServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeDispatchServer {
	mock := &MockUnsafeDispatchServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
