name: Build and publish Docker image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=$(./version.sh)
        image=docker.pkg.github.com/navikt/deployment/deployment
        docker build --tag ${image}:${version} --tag ${image}:latest .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${image}:${version}
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then
          docker push ${image}:latest
        fi
