name: Nais Deploy
on:
  pull_request:
  push:
    branches:
      - deploy-v3
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  checks:
    strategy:
      matrix:
        mise-task:
          - build
          - check:deadcode
          - check:gosec
          - check:staticcheck
          - check:vulncheck
          - test
    name: Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # ratchet:jdx/mise-action@v4
      - run: mise run ${{ matrix.mise-task }}
  release:
    name: Release GitHub Action
    if: github.ref == 'refs/heads/deploy-v3'
    needs:
      - checks
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # ratchet:jdx/mise-action@v4
      - id: version
        run: echo "tag=$(<actions/deploy/version)" >> "$GITHUB_OUTPUT"
      - run: mise run build
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git tag -f ${{ steps.version.outputs.tag }}
          git push -f --tags
      - uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # ratchet:softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          target_commitish: ${{ github.sha }}
          files: bin/deploy-action
          fail_on_unmatched_files: true
