name: Deploy Naisjob /w schedule
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "Cluster to deploy to"
        default: "ci-fss"
        required: false
        type: string

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: deploy to ${{ github.event.inputs.cluster }}
        uses: nais/deploy/actions/deploy@v2 # ratchet:exclude
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ github.event.inputs.cluster }}
          RESOURCE: testdata/naisjob.yaml
