name: Deploy Job
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "Cluster to deploy to"
        default: "ci-fss"
        required: false
        type: string

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4
      - name: deploy to ${{ github.event.inputs.cluster }}
        uses: nais/deploy/actions/deploy@v2 # ratchet:exclude
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ github.event.inputs.cluster }}
          RESOURCE: testdata/job.yaml
